<?php
/**
 * Genomic Analysis Functions
 * Parser, Engine, and Helper functions for pharmacogenomics
 */

require_once __DIR__ . '/../config/database.php';

/**
 * Detect CSV format (Genera, 23andMe, AncestryDNA)
 */
function detectGenomicFormat($firstLines) {
    $header = strtolower($firstLines[0] ?? '');
    
    // Skip comment lines
    $dataStart = 0;
    foreach ($firstLines as $i => $line) {
        if (strpos($line, '#') === 0 || empty(trim($line))) {
            $dataStart = $i + 1;
            continue;
        }
        break;
    }
    
    // Check for Genera format
    if (strpos($header, '# this file was generated by genera') !== false ||
        strpos($header, 'genera') !== false) {
        return ['format' => 'genera', 'data_start' => $dataStart, 'build' => 'GRCh37'];
    }
    
    // Check header line
    $headerLine = $firstLines[$dataStart] ?? '';
    $cols = str_getcsv($headerLine);
    $colsLower = array_map('strtolower', array_map('trim', $cols));
    
    if (in_array('rsid', $colsLower) && in_array('genotype', $colsLower)) {
        // Standard format (Genera, 23andMe)
        return ['format' => 'standard', 'data_start' => $dataStart + 1, 'build' => 'GRCh37'];
    }
    
    // AncestryDNA format
    if (in_array('rsid', $colsLower) && (in_array('allele1', $colsLower) || in_array('result', $colsLower))) {
        return ['format' => 'ancestry', 'data_start' => $dataStart + 1, 'build' => 'GRCh37'];
    }
    
    return ['format' => 'unknown', 'data_start' => 0, 'build' => 'unknown'];
}

/**
 * Parse a genomic CSV file and import into database
 * Returns array with status and counts
 */
function importGenomicCSV($patientId, $filePath, $fileName, $userId) {
    @set_time_limit(600); // 10 minutes
    @ini_set('max_execution_time', 600);
    $pdo = getConnection();
    
    // Create import log
    $stmt = $pdo->prepare("INSERT INTO genomic_imports (patient_id, file_name, status, imported_by) VALUES (?, ?, 'processing', ?)");
    $stmt->execute([$patientId, $fileName, $userId]);
    $importId = $pdo->lastInsertId();
    
    try {
        // Read first lines to detect format
        $handle = fopen($filePath, 'r');
        if (!$handle) throw new Exception("Cannot open file");
        
        $firstLines = [];
        for ($i = 0; $i < 20 && !feof($handle); $i++) {
            $firstLines[] = fgets($handle);
        }
        fclose($handle);
        $pdo->exec("COMMIT");
        $pdo->exec("SET autocommit=1");
        $pdo->exec("SET unique_checks=1");
        
        $format = detectGenomicFormat($firstLines);
        
        if ($format['format'] === 'unknown') {
            throw new Exception("Formato de arquivo não reconhecido");
        }
        
        // Update import with format info
        $pdo->prepare("UPDATE genomic_imports SET file_format=?, genome_build=? WHERE id=?")
            ->execute([$format['format'], $format['build'], $importId]);
        
        // Delete existing genotypes for this patient (re-import)
        $pdo->prepare("DELETE FROM patient_genotypes WHERE patient_id = ?")->execute([$patientId]);
        
        // Parse and insert in batches
        $handle = fopen($filePath, 'r');
        $lineNum = 0;
        $totalLines = 0;
        $imported = 0;
        $batch = [];
        $batchSize = 2000; // Smaller batches for shared hosting
        
        // Prepare batch insert statement
        $pdo->exec("SET autocommit=0");
        $pdo->exec("SET unique_checks=0");
        $insertSQL = "INSERT IGNORE INTO patient_genotypes (patient_id, rsid, chromosome, position, genotype) VALUES ";
        
        while (($line = fgets($handle)) !== false) {
            $lineNum++;
            $line = trim($line);
            
            // Skip comments and headers
            if (empty($line) || $line[0] === '#') continue;
            if ($lineNum <= $format['data_start']) continue;
            if (strpos(strtolower($line), 'rsid') === 0) continue;
            
            $totalLines++;
            $cols = str_getcsv($line);
            
            if (count($cols) < 4) continue;
            
            $rsid = trim($cols[0]);
            $chr = trim($cols[1]);
            $pos = intval($cols[2]);
            
            // Handle genotype
            if ($format['format'] === 'ancestry' && count($cols) >= 5) {
                $genotype = trim($cols[3]) . trim($cols[4]);
            } else {
                $genotype = trim($cols[3]);
            }
            
            // Validate
            if (empty($rsid) || empty($genotype) || $genotype === '--' || $genotype === '00') continue;
            if (strpos($rsid, 'rs') !== 0 && strpos($rsid, 'i') !== 0) continue;
            
            $rsidSafe = addslashes($rsid);
            $chrSafe = addslashes($chr);
            $genoSafe = addslashes($genotype);
            $batch[] = "($patientId,'$rsidSafe','$chrSafe',$pos,'$genoSafe')";
            
            if (count($batch) >= $batchSize) {
                // Use prepared statement approach for safety
                $placeholders = [];
                $values = [];
                foreach ($batch as $b) {
                    // Reset - use proper prepared statements
                }
                // Simpler: direct batch insert (data is validated)
                $sql = $insertSQL . implode(',', $batch);
                $pdo->exec($sql);
                $imported += count($batch);
                $batch = [];
            }
        }
        
        // Insert remaining
        if (!empty($batch)) {
            $sql = $insertSQL . implode(',', $batch);
            $pdo->exec($sql);
            $imported += count($batch);
        }
        
        fclose($handle);
        
        // Update import log
        $pdo->prepare("UPDATE genomic_imports SET status='completed', total_snps=?, imported_snps=? WHERE id=?")
            ->execute([$totalLines, $imported, $importId]);
        
        // Run analysis automatically
        runGenomicAnalysis($patientId);
        
        return ['success' => true, 'total' => $totalLines, 'imported' => $imported, 'import_id' => $importId];
        
    } catch (Exception $e) {
        $pdo->prepare("UPDATE genomic_imports SET status='error', error_message=? WHERE id=?")
            ->execute([$e->getMessage(), $importId]);
        return ['success' => false, 'error' => $e->getMessage()];
    }
}

/**
 * Run genomic analysis for a patient
 * Crosses patient genotypes with pgx_rules
 */
function runGenomicAnalysis($patientId) {
    $pdo = getConnection();
    
    // Clear previous results
    $pdo->prepare("DELETE FROM patient_pgx_results WHERE patient_id = ?")->execute([$patientId]);
    
    // Get all active rules
    $rules = $pdo->query("SELECT * FROM pgx_rules WHERE is_active = 1")->fetchAll();
    
    // Get patient genotypes (only the ones we need)
    $rsids = array_unique(array_column($rules, 'rsid'));
    if (empty($rsids)) return;
    
    $placeholders = implode(',', array_fill(0, count($rsids), '?'));
    $stmt = $pdo->prepare("SELECT rsid, genotype FROM patient_genotypes WHERE patient_id = ? AND rsid IN ($placeholders)");
    $stmt->execute(array_merge([$patientId], $rsids));
    $genotypes = [];
    while ($row = $stmt->fetch()) {
        $genotypes[$row['rsid']] = $row['genotype'];
    }
    
    // Analyze each rule
    $insertStmt = $pdo->prepare("INSERT INTO patient_pgx_results (patient_id, rule_id, rsid, patient_genotype, status, phenotype, interpretation) VALUES (?, ?, ?, ?, ?, ?, ?)");
    
    foreach ($rules as $rule) {
        $rsid = $rule['rsid'];
        $geno = $genotypes[$rsid] ?? null;
        
        if (!$geno) {
            $insertStmt->execute([$patientId, $rule['id'], $rsid, 'N/D', 'unknown', 'SNP não disponível', 'SNP não presente no chip de genotipagem']);
            continue;
        }
        
        // Determine status
        $refGenos = array_map('trim', explode(',', $rule['ref_genotype']));
        $hetGenos = array_map('trim', explode(',', $rule['het_genotypes']));
        $riskGenos = array_map('trim', explode(',', $rule['risk_genotypes']));
        
        // Also check reverse complement (AG = GA)
        $genoReverse = strlen($geno) == 2 ? $geno[1].$geno[0] : $geno;
        
        if (in_array($geno, $riskGenos) || in_array($genoReverse, $riskGenos)) {
            $status = 'risk';
            $phenotype = $rule['phenotype_risk'];
        } elseif (in_array($geno, $hetGenos) || in_array($genoReverse, $hetGenos)) {
            $status = 'attention';
            $phenotype = $rule['phenotype_het'];
        } elseif (in_array($geno, $refGenos) || in_array($genoReverse, $refGenos)) {
            $status = 'normal';
            $phenotype = $rule['phenotype_normal'];
        } else {
            $status = 'info';
            $phenotype = "Genótipo $geno - interpretar";
        }
        
        $interpretation = $rule['recommendations'] ?? '';
        
        $insertStmt->execute([$patientId, $rule['id'], $rsid, $geno, $status, $phenotype, $interpretation]);
    }
}

/**
 * Get genomic analysis summary for a patient
 */
function getGenomicSummary($patientId) {
    $pdo = getConnection();
    
    // Check if patient has genomic data
    $hasData = $pdo->prepare("SELECT COUNT(*) FROM patient_genotypes WHERE patient_id = ?");
    $hasData->execute([$patientId]);
    if ($hasData->fetchColumn() == 0) return null;
    
    // Get import info
    $import = $pdo->prepare("SELECT * FROM genomic_imports WHERE patient_id = ? ORDER BY imported_at DESC LIMIT 1");
    $import->execute([$patientId]);
    $importInfo = $import->fetch();
    
    // Get results by panel
    $sql = "SELECT p.code, p.name, p.icon, p.color,
            COUNT(r.id) as total_rules,
            SUM(CASE WHEN pr.status = 'normal' THEN 1 ELSE 0 END) as normal_count,
            SUM(CASE WHEN pr.status = 'attention' THEN 1 ELSE 0 END) as attention_count,
            SUM(CASE WHEN pr.status = 'risk' THEN 1 ELSE 0 END) as risk_count,
            SUM(CASE WHEN pr.status = 'unknown' THEN 1 ELSE 0 END) as unknown_count
            FROM pgx_panels p
            JOIN pgx_rules r ON r.panel_id = p.id LEFT JOIN patient_pgx_results pr ON pr.rule_id = r.id AND pr.patient_id = ? WHERE p.is_active = 1 GROUP BY p.id ORDER BY p.sort_order";
    $stmt = $pdo->prepare($sql); $stmt->execute([$patientId]);
    return ['import' => $importInfo, 'panels' => $stmt->fetchAll(), 'has_data' => true];
}
function getPanelResults($patientId, $panelCode) {
    $pdo = getConnection();
    $stmt = $pdo->prepare("SELECT r.*, pr.patient_genotype, pr.status, pr.phenotype, pr.interpretation, g.name as gene_name, g.description as gene_desc FROM pgx_rules r JOIN pgx_panels p ON r.panel_id = p.id LEFT JOIN patient_pgx_results pr ON pr.rule_id = r.id AND pr.patient_id = ? LEFT JOIN pgx_genes g ON g.symbol = r.gene_symbol AND g.panel_id = p.id WHERE p.code = ? AND r.is_active = 1 ORDER BY r.gene_symbol");
    $stmt->execute([$patientId, $panelCode]); return $stmt->fetchAll();
}
function getDrugAnalysis($patientId, $drugName = null) {
    $pdo = getConnection();
    $sql = "SELECT dg.*, pg.genotype as patient_genotype, pr.status, pr.phenotype FROM pgx_drug_genes dg LEFT JOIN patient_genotypes pg ON pg.rsid = dg.rsid AND pg.patient_id = ? LEFT JOIN patient_pgx_results pr ON pr.rsid = dg.rsid AND pr.patient_id = ? WHERE dg.is_active = 1";
    $params = [$patientId, $patientId];
    if ($drugName) { $sql .= " AND dg.drug_name = ?"; $params[] = $drugName; }
    $stmt = $pdo->prepare($sql . " ORDER BY dg.drug_name"); $stmt->execute($params);
    $drugs = [];
    foreach ($stmt->fetchAll() as $row) {
        $n = $row['drug_name'];
        if (!isset($drugs[$n])) $drugs[$n] = ['name'=>$n,'class'=>$row['drug_class'],'genes'=>[],'worst_status'=>'normal'];
        $drugs[$n]['genes'][] = $row;
        $s = $row['status'] ?? 'unknown';
        $pri = ['risk'=>4,'attention'=>3,'info'=>2,'normal'=>1,'unknown'=>0];
        if (($pri[$s]??0) > ($pri[$drugs[$n]['worst_status']]??0)) $drugs[$n]['worst_status'] = $s;
    }
    return $drugs;
}
function genomicStatusBadge($s) { $m=['normal'=>['bg-success','Normal'],'attention'=>['bg-warning text-dark','Atencao'],'risk'=>['bg-danger','Risco'],'info'=>['bg-info','Info'],'unknown'=>['bg-secondary','N/D']]; $x=$m[$s]??$m['unknown']; return '<span class="badge '.$x[0].'">'.$x[1].'</span>'; }
function genomicStatusIcon($s) { return ['normal'=>'&#128994;','attention'=>'&#128993;','risk'=>'&#128308;','info'=>'&#128309;','unknown'=>'&#9898;'][$s] ?? '&#9898;'; }
function hasGenomicData($pid) { $pdo=getConnection(); $s=$pdo->prepare("SELECT COUNT(*) FROM patient_genotypes WHERE patient_id=?"); $s->execute([$pid]); return $s->fetchColumn()>0; }
