-- v3.1 FINAL 71 rules GSA v3.0
DELETE FROM patient_pgx_results;
DELETE FROM pgx_rules;

INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'CYP1A2','rs762551','*1F','CC','AC','AA','Met normal','Met interm','Met ultra-rapido','moderate','2A','Melatonina lib prolongada.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'CYP2C9','rs1799853','*2','CC','CT','TT','Met normal','Met interm','Met lento','high','1A','Varfarina dose menor.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'CYP2C9','rs1057910','*3','AA','AC','CC','Met normal','Met interm','Met muito lento','high','1A','Varfarina muito menor.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'CYP2C19','rs4244285','*2','GG','GA','AA','Met normal','Met interm LOF','Met lento LOF','high','1A','Clopidogrel prasugrel.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'CYP2C19','rs4986893','*3','GG','GA','AA','Met normal','Met interm LOF','Met lento LOF','high','1A','Clopidogrel ineficaz.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'CYP2C19','rs12248560','*17','CC','CT','TT','Met normal','Met rapido GOF','Met ultra-rapido','high','1A','Escitalopram -30-40%.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'CYP2D6','rs3892097','*4','GG','GA','AA','Met normal','Met interm','Met nulo','high','1A','Atomoxetina acumular.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'CYP2D6','rs16947','*2','CC,GG','AG,CT','TT,AA','Normal','Func het','Func hom','low','2B','Sem impacto.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'CYP2D6','rs1065852','*10','CC','CT','TT','Met normal','Met reduz','Met muito reduz','moderate','2A','CYP2D6 acumular.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'CYP3A4','rs35599367','*22','CC,GG','CT,AG','TT,AA','Met normal','Met reduz','Met muito reduz','moderate','2A','Tacrolimus acum.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'CYP3A4','rs2740574','*1B','AA,TT','AG,TC','GG,CC','Normal','Exp aum','Exp muito aum','low','3','Met aum.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'CYP3A5','rs776746','*3','GG,AA','AG,TC','CC,TT','Nao-exp','Exp parcial','Expressor','moderate','1A','Tacrolimus 1.5-2x.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'CYP4F2','rs2108622','*3','CC','CT','TT','Normal','VitK reduz','VitK muito reduz','moderate','2A','Varfarina maior.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'DPYD','rs3918290','*2A','GG','GA','AA','DPD ok','DPD defic','DPD deficiente','high','1A','CONTRA-INDICAR 5-FU.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'DPYD','rs67376798','D949V','AA','AT','TT','Normal','DPD reduz','DPD deficiente','high','1A','Verificar fluoropir.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'TPMT','rs1800462','*2','CC','CG','GG','Normal','TPMT reduz','TPMT defic','high','1A','Azatioprina reduzir.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'TPMT','rs1800460','*3B','CC','CT','TT','Normal','TPMT reduz','TPMT defic','high','1A','Azatioprina reduzir.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'TPMT','rs1142345','*3C','AA','AG','GG','Normal','TPMT reduz','TPMT defic','high','1A','Azatioprina reduzir.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'UGT1A6','rs2070959','T181A','AA','AG','GG','Normal','VPA alt','Muito alt','moderate','3','Dosar valproato.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'UGT1A6','rs1105879','R184S','GG','AG','AA','Normal','Met alt','Muito alt','moderate','3','Dosar valproato.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'UGT2B15','rs1902023','D85Y','CC','CT','TT','Normal','BZD reduz','Muito reduz','moderate','2B','Lorazepam menor.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'VKORC1','rs9923231','-1639','GG','GA','AA','Normal','Sensivel','Muito sensivel','high','1A','Varfarina -25-50%.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'ABCB1','rs1045642','C3435T','AA','AG','GG','P-gp ok','P-gp interm','P-gp reduz','moderate','2B','P-gp biodisponib.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'ABCG2','rs2231142','Q141K','GG','GT','TT','BCRP ok','BCRP reduz','Muito reduz','moderate','2A','Rosuvastatina menor.','GSA-v3+dbSNP');
INSERT INTO pgx_rules (panel_id,gene_symbol,rsid,variant_name,ref_genotype,het_genotypes,risk_genotypes,phenotype_normal,phenotype_het,phenotype_risk,clinical_significance,evidence_level,recommendations,source) VALUES (1,'SLCO1B1','rs4149056','*5','TT','TC','CC','Normal','Reduzida','Muito reduz','high','1A','Sinvastatina max 20mg.','GSA-v3+dbSNP');