# Generate pgx_rules SQL seed file
rules = []
def R(p,g,r,v,ref,het,risk,pn,ph,pr,cs,ev,rec):
    rules.append((p,g,r,v,ref,het,risk,pn,ph,pr,cs,ev,rec))

# PHARMACO (1)
R(1,'CYP1A2','rs762551','*1F','CC','AC','AA','Met normal','Met interm','Met ultra-rapido','moderate','2A','Melatonina lib prolongada.')
R(1,'CYP2B6','rs3745274','*6','GG','GT','TT','Met normal','Met interm','Met lento','moderate','2A','Bupropiona pode acumular.')
R(1,'CYP2C9','rs1799853','*2','CC','CT','TT','Met normal','Met interm','Met lento','high','1A','Varfarina dose menor.')
R(1,'CYP2C9','rs1057910','*3','AA','AC','CC','Met normal','Met interm','Met muito lento','high','1A','Varfarina dose muito menor.')
R(1,'CYP2C19','rs4244285','*2','GG','GA','AA','Met normal','Met interm LOF','Met lento LOF','high','1A','Clopidogrel ineficaz.')
R(1,'CYP2C19','rs4986893','*3','GG','GA','AA','Met normal','Met interm LOF','Met lento LOF','high','1A','Clopidogrel ineficaz.')
R(1,'CYP2C19','rs12248560','*17','CC','CT','TT','Met normal','Met rapido GOF','Met ultra-rapido','high','1A','Escitalopram/sertralina niveis -30-40%.')
R(1,'CYP2D6','rs3892097','*4','GG','GA','AA','Met normal','Met interm','Met nulo','high','1A','Atomoxetina acumular. Codeina ineficaz.')
R(1,'CYP2D6','rs16947','*2','CC','AG','GG','Normal','Funcional','Funcional','low','2B','Sem impacto negativo.')
R(1,'CYP2D6','rs1065852','*10','CC','CT','TT','Met normal','Met reduzido','Met muito reduz','moderate','2A','Substratos CYP2D6 acumular.')
R(1,'CYP2D6','rs28371725','*41','CC','CG','GG','Met normal','Met interm','Met reduzido','moderate','2A','Funcao reduzida.')
R(1,'CYP3A4','rs35599367','*22','CC','CT','TT','Met normal','Met reduzido','Met muito reduz','moderate','2A','Tacrolimus acumular.')
R(1,'CYP3A4','rs2740574','*1B','AA','AG','GG','Normal','Expressao aum','Expressao muito aum','low','3','Met aumentado.')
R(1,'CYP3A5','rs776746','*3','TT','CT','CC','Nao-expressor','Exp parcial','Expressor','moderate','1A','Tacrolimus dose 1.5-2x.')
R(1,'CYP4F2','rs2108622','*3','CC','CT','TT','Normal','Met vitK reduz','Met vitK muito reduz','moderate','2A','Varfarina dose maior.')
R(1,'DPYD','rs3918290','*2A','GG','GA','AA','DPD normal','DPD defic parcial','DPD deficiente','high','1A','CONTRA-INDICAR 5-FU.')
R(1,'DPYD','rs55886062','*13','CC','CT','TT','Normal','DPD reduzida','DPD deficiente','high','1A','Reduzir fluoropirimidinas.')
R(1,'DPYD','rs67376798','D949V','AA','AT','TT','Normal','DPD reduzida','DPD deficiente','high','1A','Reduzir fluoropirimidinas.')
R(1,'TPMT','rs1800462','*2','CC','CG','GG','Normal','TPMT reduzida','TPMT deficiente','high','1A','Azatioprina dose reduzir.')
R(1,'TPMT','rs1800460','*3B','CC','CT','TT','Normal','TPMT reduzida','TPMT deficiente','high','1A','Azatioprina dose reduzir.')
R(1,'TPMT','rs1142345','*3C','AA','AG','GG','Normal','TPMT reduzida','TPMT deficiente','high','1A','Azatioprina dose reduzir.')
R(1,'UGT1A6','rs2070959','T181A','AA','AG','GG','Normal','Met valproato alt','Met alt','moderate','3','Dosar niveis valproato.')
R(1,'UGT1A6','rs1105879','R184S','GG','AG','AA','Normal','Met alt','Met alt','moderate','3','Dosar niveis valproato.')
R(1,'UGT2B15','rs1902023','D85Y','CC','CT','TT','Normal','Met BZD reduz','Met BZD muito reduz','moderate','2B','Lorazepam dose menor.')
R(1,'VKORC1','rs9923231','-1639G>A','GG','GA','AA','Normal','Sensivel varfarina','Muito sensivel','high','1A','Varfarina dose 25-50% menor.')
R(1,'ABCB1','rs1045642','C3435T','CC','CT','TT','P-gp normal','P-gp interm','P-gp reduzida','moderate','2B','Substratos P-gp biodisponib aum.')
R(1,'ABCG2','rs2231142','Q141K','GG','GT','TT','BCRP normal','BCRP reduzida','BCRP muito reduz','moderate','2A','Rosuvastatina dose menor.')
R(1,'SLCO1B1','rs4149056','*5','TT','TC','CC','Normal','Funcao reduzida','Funcao muito reduz','high','1A','Sinvastatina max 20mg.')

# NEURO (2)
R(2,'COMT','rs4680','Val158Met','GG','AG','AA','Alta ativ Val/Val','Interm Val/Met','Baixa ativ Met/Met','moderate','2A','Val/Val: resp estimulantes.')
R(2,'BDNF','rs6265','Val66Met','CC','CT','TT','Normal Val/Val','Secrecao reduz','Secrecao muito reduz','moderate','2B','Exercicio fisico.')
R(2,'SLC6A4','rs25531','5-HTTLPR','AA','AG','GG','Alta expressao','Expressao interm','Baixa expressao','moderate','2B','ISRS demoram mais.')
R(2,'HTR1A','rs6295','C-1019G','CC','CG','GG','Normal','Resp ISRS -30%','Resp ISRS muito reduz','moderate','2B','Considerar duloxetina.')
R(2,'HTR2A','rs6311','A-1438G','GG','AG','AA','Normal','Variante','Hom variante','low','3','Ajuste antidepressivos.')
R(2,'HTR2C','rs3813929','-759C/T','CC','CT','TT','Risco peso padrao','Protecao parcial','Protecao peso','moderate','2B','CC: monitorar peso.')
R(2,'DRD2','rs6277','C957T','CC','CT','TT','Normal','mRNA instavel','mRNA muito inst','low','3','Resp antipsicoticos.')
R(2,'ANKK1','rs1800497','TaqIA','GG','AG','AA','D2 normal','D2 reduz ~30%','D2 muito reduz','moderate','2B','Menor resp antipsicoticos.')
R(2,'ADRA2A','rs1800544','C-1291G','CC','CG','GG','Normal','Resp Ritalina var','Resp Ritalina alt','moderate','3','Monitorar Ritalina.')
R(2,'CES1','rs2244613','Intronico','CC','CT','TT','Normal','Duracao Ritalina alt','Duracao muito alt','moderate','3','Observar duracao.')
R(2,'FKBP5','rs1360780','Intron 7','CC','CT','TT','Normal','Eixo HPA desreg','Eixo HPA muito desreg','moderate','2B','Sono, exercicio.')
R(2,'FKBP5','rs3800373','3UTR','AA','AC','CC','Normal','HPA variante','HPA variante','moderate','2B','Manejo estresse.')
R(2,'FKBP5','rs9296158','Intronico','AA','AG','GG','Normal','HPA variante','HPA variante','moderate','2B','Manejo estresse.')
R(2,'FKBP5','rs9470080','Intronico','CC','CT','TT','Normal','HPA variante','HPA variante','moderate','2B','Manejo estresse.')
R(2,'GSK3B','rs334558','-50T/C','TT','TC','CC','Resp litio padrao','Boa resp litio','Melhor resp litio','moderate','3','Litio eficaz.')
R(2,'GRIK4','rs1954787','Intronico','CC','CT','TT','Normal','Resp citalopram var','Resp var','low','3','Monitorar citalopram.')
R(2,'OPRM1','rs1799971','A118G','AA','AG','GG','Normal','Menor afin opioides','Afin muito reduz','moderate','2A','Dose maior opioides.')
R(2,'OPRD1','rs1042114','Intronico','GG','AG','AA','Normal','Dor alterada','Muito alterada','low','3','Informar procedimentos.')
R(2,'OPRD1','rs678849','Intronico','CC','CT','TT','Normal','Dor modulada','Dor modulada','low','3','Informar.')
R(2,'SLC6A2','rs5569','A1287G','AA','AG','GG','Normal','NET variante','NET variante','low','3','Monitorar atomoxetina.')
R(2,'DRD1','rs4532','A-48G','AA','AG','GG','Normal','Func exec var','Func exec alt','low','3','Treino func executivas.')

# CARDIO (3)
R(3,'ACE','rs4343','A2350G','AA','AG','GG','Normal','ACE interm','ACE elevado','moderate','2B','Beneficio iECAs.')
R(3,'ADD1','rs4961','G460W','GG','GT','TT','Normal','Sensib sodio','Alta sensib','moderate','3','Dieta hipossodica.')
R(3,'AGT','rs699','M235T','AA','AG','GG','Normal','Risco leve HAS','Risco mod HAS','moderate','2B','Monitorar PA.')
R(3,'AGTR1','rs5186','A1166C','AA','AC','CC','Normal','Variante','Resp BRA alt','low','3','Monitorar losartana.')
R(3,'F5','rs6025','FV Leiden','CC','CT','TT','SEM Leiden','HET Leiden','HOM Leiden','high','1A','Het: risco 5-7x. Evitar ACO.')
R(3,'F2','rs1799963','G20210A','GG','GA','AA','Normal','Risco trombose aum','Alto risco','high','1A','Profilaxia.')
R(3,'APOA5','rs662799','-1131T>C','AA','AG','GG','Normal','Risco TG','Alto risco TG','moderate','2B','Monitorar TG.')
R(3,'GNB3','rs5443','C825T','CC','CT','TT','Normal','Resp diur var','Melhor resp tiaz','low','3','Tiazidicos.')
R(3,'NOS1AP','rs12143842','Intronico','TT','CT','CC','Normal','Risco QT','Alto risco QT','moderate','2A','EVITAR farmacos QT.')
R(3,'NOS1AP','rs10494366','Intronico','TT','GT','GG','Normal','QT variante','QT variante','low','3','Monitorar QT.')
R(3,'HMGCR','rs12916','Intronico','TT','CT','CC','Normal','Resp estatinas mod','Resp mod','low','3','Estatinas.')
R(3,'KIF6','rs20455','Trp719Arg','AA','AG','GG','Normal','Arg carrier','Arg hom','low','3','Estatinas beneficio.')
R(3,'ADRB2','rs1042713','Arg16Gly','AA','AG','GG','Arg/Arg','Arg/Gly','Gly/Gly','moderate','2B','Salbutamol cronico.')
R(3,'ADRB2','rs1042714','Gln27Glu','CC','CG','GG','Gln/Gln','Gln/Glu','Glu/Glu','low','3','Broncodilatadores.')
R(3,'NEDD4L','rs4149601','Intronico','GG','AG','AA','Normal','PA variante','PA variante','low','3','PA.')
R(3,'PLCD3','rs12946454','Intronico','AA','AG','GG','Normal','PA variante','PA variante','low','3','PA.')
R(3,'MC4R','rs17782313','Near MC4R','TT','CT','CC','Normal','Risco obesidade','Alto risco','moderate','2B','Dieta e exercicio.')

# ONCO (4)
R(4,'XPC','rs2228001','Lys939Gln','AA','AC','CC','Reparo normal','Reparo reduz','Reparo muito reduz','moderate','2B','Protetor solar FPS50+.')
R(4,'XPC','rs2228000','Ala499Val','CC','CT','TT','Normal','Reparo reduz','Reparo muito reduz','moderate','2B','Protecao solar.')
R(4,'GSTP1','rs1695','Ile105Val','AA','AG','GG','Normal','Detox reduzida','Detox muito reduz','moderate','2B','Cruciferas na dieta.')
R(4,'GSTP1','rs1138272','Ala114Val','CC','CT','TT','Normal','GSTP1 reduzida','GSTP1 deficiente','moderate','3','Dieta antioxidante.')
R(4,'EPHX1','rs1051740','Tyr113His','TT','CT','CC','Normal','Ativ reduzida','Ativ muito reduz','moderate','3','Evitar pesticidas.')
R(4,'RARG','rs2229774','Ser427Leu','CC','CT','TT','Normal','Risco cardiotox','Alto