-- SEED: Genes por Painel
-- panel_id: 1=pharmaco,2=neuro,3=cardio,4=onco,5=nutri,6=musculo,7=derma,8=immuno,9=endocrino,10=sleep

INSERT INTO `pgx_genes` (`symbol`,`name`,`chromosome`,`description`,`panel_id`) VALUES
-- FARMACOGENOMICA (1)
('CYP1A2','Cytochrome P450 1A2','15','Melatonina, cafeina, clozapina',1),
('CYP2B6','Cytochrome P450 2B6','19','Bupropiona, efavirenz',1),
('CYP2C9','Cytochrome P450 2C9','10','Varfarina, AINEs, losartana',1),
('CYP2C19','Cytochrome P450 2C19','10','Escitalopram, sertralina, clopidogrel, omeprazol',1),
('CYP2D6','Cytochrome P450 2D6','22','Atomoxetina, codeina, antidepressivos (~25% farmacos)',1),
('CYP3A4','Cytochrome P450 3A4','7','Principal enzima hepatica (~50% farmacos)',1),
('CYP3A5','Cytochrome P450 3A5','7','Tacrolimus, ciclosporina',1),
('CYP4F2','Cytochrome P450 4F2','19','Vitamina K, varfarina',1),
('DPYD','Dihydropyrimidine Dehydrogenase','1','5-fluorouracil. Deficiencia=fatal',1),
('TPMT','Thiopurine Methyltransferase','6','Azatioprina, 6-MP',1),
('UGT1A4','UDP-Glucuronosyltransferase 1A4','2','Lamotrigina',1),
('UGT1A6','UDP-Glucuronosyltransferase 1A6','2','Valproato, paracetamol',1),
('UGT2B15','UDP-Glucuronosyltransferase 2B15','4','Lorazepam, oxazepam',1),
('VKORC1','Vitamin K Epoxide Reductase','16','Alvo varfarina',1),
('ABCB1','P-glycoprotein MDR1','7','Bomba efluxo, barreira hematoencefalica',1),
('ABCG2','BCRP','4','Efluxo rosuvastatina, acido urico',1),
('SLCO1B1','OATP1B1','12','Transportador hepatico, miopatia estatinas',1),
-- NEUROPSIQUIATRIA (2)
('COMT','Catechol-O-Methyltransferase','22','Dopamina cortex pre-frontal',2),
('BDNF','Brain-Derived Neurotrophic Factor','11','Neuroplasticidade, memoria',2),
('SLC6A4','Serotonin Transporter 5-HTT','17','Alvo ISRS',2),
('SLC6A2','Norepinephrine Transporter NET','16','Alvo atomoxetina',2),
('HTR1A','Serotonin Receptor 1A','5','Ansiedade, resposta ISRS',2),
('HTR2A','Serotonin Receptor 2A','13','Antipsicoticos, antidepressivos',2),
('HTR2C','Serotonin Receptor 2C','X','Ganho peso antipsicoticos',2),
('DRD1','Dopamine Receptor D1','5','Funcao executiva',2),
('DRD2','Dopamine Receptor D2','11','Antipsicoticos, recompensa',2),
('ANKK1','ANKK1/DRD2 TaqIA','11','Densidade receptores D2',2),
('ADRA2A','Alpha-2A Adrenergic Receptor','10','Resposta metilfenidato',2),
('CES1','Carboxylesterase 1','16','Metabolismo metilfenidato',2),
('FKBP5','FK506 Binding Protein 5','6','Eixo HPA estresse',2),
('GSK3B','Glycogen Synthase Kinase 3-Beta','3','Resposta litio',2),
('GRIK4','Glutamate Receptor Kainate 4','11','Resposta citalopram',2),
('OPRM1','Mu Opioid Receptor','6','Resposta opioides',2),
('OPRD1','Delta Opioid Receptor','1','Modulacao dor',2),
-- CARDIOLOGIA (3)
('ACE','Angiotensin-Converting Enzyme','17','Sistema renina-angiotensina',3),
('AGT','Angiotensinogen','1','Hipertensao',3),
('AGTR1','Angiotensin II Receptor Type 1','3','Resposta BRAs',3),
('ADD1','Alpha-Adducin','4','Sensibilidade sodio',3),
('ADRB2','Beta-2 Adrenergic Receptor','5','Broncodilatadores',3),
('F5','Coagulation Factor V','1','Fator V Leiden, trombofilia',3),
('F2','Prothrombin','11','Protrombina G20210A',3),
('APOE','Apolipoprotein E','19','Alzheimer, colesterol',3),
('APOA5','Apolipoprotein A-V','11','Triglicerideos',3),
('GNB3','G-Protein Beta-3','12','Diureticos, hipertensao',3),
('NOS1AP','NOS1 Adaptor Protein','1','Intervalo QT',3),
('NEDD4L','NEDD4-Like E3 Ligase','18','Canais sodio, PA',3),
('PLCD3','Phospholipase C Delta 3','17','Pressao arterial',3),
('HMGCR','HMG-CoA Reductase','5','Alvo estatinas',3),
('KIF6','Kinesin Family Member 6','6','Resposta estatinas',3),
('PCSK9','Proprotein Convertase 9','1','Colesterol LDL',3),
('LPA','Lipoprotein(a)','6','Risco aterosclerose',3),
-- ONCOLOGIA (4)
('BRCA1','BRCA1 DNA Repair','17','Cancer mama/ovario hereditario',4),
('BRCA2','BRCA2 DNA Repair','13','Cancer mama/ovario/prostata',4),
('TP53','Tumor Protein P53','17','Sindrome Li-Fraumeni',4),
('APC','Adenomatous Polyposis Coli','5','Polipose adenomatosa familiar',4),
('MLH1','MutL Homolog 1','3','Lynch - cancer colorretal',4),
('MSH2','MutS Homolog 2','2','Lynch - cancer colorretal',4),
('CHEK2','Checkpoint Kinase 2','22','Cancer mama',4),
('XPC','Xeroderma Pigmentosum C','3','Reparo DNA UV',4),
('GSTP1','Glutathione S-Transferase Pi','11','Detoxificacao',4),
('EPHX1','Epoxide Hydrolase 1','1','Metabolismo carcinogenos',4),
('RARG','Retinoic Acid Receptor Gamma','12','Cardiotox antraciclinas',4),
('SLC28A3','Nucleoside Transporter','9','Cardiotox quimio protetor',4),
-- NUTRIGENOMICA (5)
('MTHFR','Methylenetetrahydrofolate Reductase','1','Folato, homocisteina',5),
('MTRR','Methionine Synthase Reductase','5','Metabolismo B12',5),
('VDR','Vitamin D Receptor','12','Metabolismo vitamina D',5),
('FUT2','Fucosyltransferase 2','19','Absorcao B12',5),
('BCMO1','Beta-Carotene Oxygenase 1','16','Conversao beta-caroteno em vit A',5),
('MCM6','Minichromosome Maintenance 6','2','Lactase persistencia',5),
('HFE','Homeostatic Iron Regulator','6','Hemocromatose',5),
-- MUSCULOESQUELETICO (6)
('ACTN3','Alpha-Actinin-3','11','Fibras rapidas vs resistencia',6),
('COL1A1','Collagen Type I Alpha 1','17','Densidade ossea, osteoporose',6),
('COL5A1','Collagen Type V Alpha 1','9','Flexibilidade, lesoes tendao',6),
('GDF5','Growth Differentiation Factor 5','20','Osteoartrite',6),
-- DERMATOLOGIA (7)
('MC1R','Melanocortin 1 Receptor','16','Pigmentacao, ruivismo, melanoma',7),
('TYR','Tyrosinase','11','Albinismo, pigmentacao',7),
('OCA2','OCA2 Melanosomal Protein','15','Cor olhos, pele',7),
('SLC45A2','Solute Carrier 45A2','5','Pigmentacao pele',7),
-- IMUNOLOGIA (8)
('HLA-A','HLA Class I A','6','Hipersensibilidade carbamazepina',8),
('HLA-B','HLA Class I B','6','Hipersensibilidade abacavir, alopurinol',8),
('HLA-DQ','HLA Class II DQ','6','Doenca celiaca',8),
('BDKRB1','Bradykinin Receptor B1','14','Tosse iECA, inflamacao',8),
-- ENDOCRINOLOGIA (9)
('TCF7L2','Transcription Factor 7-Like 2','10','Diabetes tipo 2',9),
('PPARG','Peroxisome Proliferator-Activated Receptor Gamma','3','Sensibilidade insulina',9),
('MC4R','Melanocortin 4 Receptor','18','Apetite, obesidade',9),
('DIO2','Type II Deiodinase','14','Conversao T4 em T3',9),
('G6PD','Glucose-6-Phosphate Dehydrogenase','X','Deficiencia G6PD, hemolise',9),
-- SONO (10)
('PER2','Period Circadian Regulator 2','2','Cronotipo, ritmo circadiano',10),
('CLOCK','Clock Circadian Regulator','4','Gene relogio biologico',10),
('ADA','Adenosine Deaminase','20','Pressao homeost sono',10);