-- =============================================
-- MEDIC - Seed de Detalhes de Medicamentos (Lote 14 de N)
-- 10 medicamentos: Fosfenitoína → Fenofibrato
-- Pode ser rodado múltiplas vezes com segurança
-- =============================================

SET NAMES utf8mb4;

-- =============================================
-- PARTE A: Inserir medicamentos na pgx_drug_genes
-- =============================================

INSERT IGNORE INTO `pgx_drug_genes` (`drug_name`, `drug_class`, `gene_symbol`, `rsid`, `interaction_type`, `effect_description`, `recommendation_normal`, `recommendation_het`, `recommendation_risk`, `evidence_level`, `source`, `is_active`) VALUES
('Fosfenitoína', 'Anticonvulsivantes', 'CYP2C9', 'rs1799853', 'substrate', 'CYP2C9 metaboliza fenitoína (pró-droga) - lentos acumulam', 'Dose padrão', 'Metabolismo reduzido - dose menor', 'Risco de toxicidade - reduzir dose significativamente', '1A', 'CPIC', 1),
('Fosfenitoína', 'Anticonvulsivantes', 'HLA-B', 'rs3909184', 'risk', 'HLA-B*15:02 associado a SJS/TEN - risco em asiáticos', 'Sem risco (europeus)', 'Baixo risco', 'Tipagem HLA em asiáticos', '1A', 'CPIC', 1),
('Fluvoxamina', 'Antidepressivos (ISRS)', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza fluvoxamina parcialmente', 'Dose padrão', 'Monitorar', 'Monitorar', '2B', 'PharmGKB', 1),
('Flutamida', 'Antineoplásicos (Antiandrogênicos)', 'G6PD', 'rs1050829', 'risk', 'G6PD deficiente - flutamida pode causar hemólise', 'Sem risco', 'Cautela', 'Monitorar', '3', 'PharmGKB', 1),
('Flurbiprofeno', 'Anti-inflamatórios (AINEs)', 'CYP2C9', 'rs1799853', 'substrate', 'CYP2C9 metaboliza flurbiprofeno', 'Dose padrão', 'Meia-vida prolongada', 'Risco de sangramento', '2A', 'DPWG', 1),
('Fluoxetina', 'Antidepressivos (ISRS)', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza fluoxetina + é INIBIDOR POTENTE do CYP2D6', 'Dose padrão', 'Monitorar', 'Considerar alternativa', '1A', 'CPIC', 1),
('Fluoxetina', 'Antidepressivos (ISRS)', 'FKBP5', 'rs1360780', 'target', 'FKBP5 modula resposta a antidepressivos', 'Resposta favorável', 'Eixo HPA desregulado', 'Resposta reduzida', '2B', 'PharmGKB', 1),
('Fluoruracila', 'Antineoplásicos', 'DPYD', 'rs3918290', 'substrate', 'DPD metaboliza 5-FU - deficiência causa toxicidade FATAL', 'Dose padrão', 'Reduzir dose 25-50%', 'CONTRAINDICADO', '1A', 'CPIC', 1),
('Flufenazina', 'Antipsicóticos', 'CYP1A2', 'rs762551', 'substrate', 'CYP1A2 metaboliza flufenazina - ultra-rápidos eliminam mais rápido', 'Dose padrão', 'Metabolismo aumentado', 'Pode necessitar dose maior', '2B', 'PharmGKB', 1),
('Flecainida', 'Antiarrítmicos', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza flecainida - lentos têm mais efeito/toxicidade', 'Dose padrão', 'Monitorar ECG', 'Reduzir dose - risco pró-arrítmico', '1A', 'DPWG', 1),
('Fentanil', 'Analgésicos Opioides', 'CYP3A4', 'rs35599367', 'substrate', 'CYP3A4 metaboliza fentanil', 'Dose padrão', 'Metabolismo reduzido', 'Risco de acúmulo', '2A', 'PharmGKB', 1),
('Fentanil', 'Analgésicos Opioides', 'OPRM1', 'rs2952768', 'target', 'rs2952768 modula dose de opioide necessária', 'Dose padrão', 'Pode necessitar dose maior', 'Dose maior', '3', 'GWAS', 1),
('Fenofibrato', 'Fibratos (Dislipidemia)', 'APOA5', 'rs964184', 'target', 'APOA5 modula resposta de triglicerídeos a fibratos', 'Resposta padrão', 'Pode ter melhor resposta (TG altos)', 'Melhor resposta se TG basalmente elevados', '2B', 'PharmGKB', 1);

-- =============================================
-- PARTE B: Detalhes dos medicamentos (resumidos - 5 principais)
-- =============================================

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Fosfenitoína', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Cerebyx®, Sesquient®', 'A fosfenitoína é uma pró-droga da fenitoína utilizada IV para status epilepticus e convulsões. É convertida em fenitoína, que é metabolizada pelo CYP2C9 e CYP2C19. O CPIC tem guideline para fenitoína baseado no CYP2C9. HLA-B*15:02 associado a SJS em asiáticos.', 'CYP2C9 (CC = *1/*1) = Metabolizador NORMAL. Fenitoína processada adequadamente. HLA-B*15:02 proxy GG = provavelmente negativo (risco SJS muito baixo em europeus).', 'rs1799853', '10', 'CYP2C9', 'Europeia', 'CYP2C9 e Fenitoína (CPIC):\n- *1/*1 = Normal (dose padrão)\n- *1/*2 = Intermediário (monitorar níveis)\n- *1/*3 ou *2/*2 = Lento (reduzir dose 25%)\n- *2/*3 ou *3/*3 = Muito lento (reduzir dose 50%)', 'CYP2C9 normal + risco SJS muito baixo (europeu). Fenitoína/fosfenitoína pode ser usada em dose padrão. Monitorar níveis séricos conforme protocolo (janela 10-20 mcg/mL).', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Fluoxetina', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Prozac®, Daforin®, Depress®, Prozen®', 'A fluoxetina é um ISRS com meia-vida muito longa (~4-6 dias, metabólito ativo norfluoxetina ~16 dias). É metabolizada pelo CYP2D6 e é INIBIDORA POTENTE do CYP2D6. FKBP5 e BDNF modulam resposta. Menos dependente do CYP2C19 que sertralina. Efeitos adversos incluem insônia, agitação, náuseas, disfunção sexual e ativação em jovens.', 'CYP2D6 N/D (mas fluoxetina inibe o CYP2D6 — autoinibição pode compensar parcialmente). FKBP5 CC = eixo HPA normal (favorável). BDNF CC = secreção normal (favorável). HTR1A CG = resposta ISRS -30% (desfavorável). SLC6A4 N/D.', 'rs3892097', '22', 'CYP2D6', 'Europeia', 'CYP2D6: N/D (fluoxetina é inibidora potente do CYP2D6)\nFKBP5 rs1360780: CC = Normal (favorável)\nBDNF rs6265: CC = Normal (favorável)\nHTR1A rs6295: CG = Resposta ISRS reduzida ~30%', 'RELEVANTE PARA AUTISMO: FKBP5 e BDNF normais são favoráveis. PORÉM HTR1A CG sugere resposta a ISRS -30%. A fluoxetina tem vantagem de ser MENOS dependente do CYP2C19 que a sertralina (que sofre impacto do *17). Se ISRS for necessário e sertralina não funcionar (por CYP2C19 rápido), fluoxetina é alternativa razoável. ATENÇÃO: Fluoxetina INIBE o CYP2D6 — não usar com tamoxifeno nem com outros substratos do CYP2D6.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Fluoruracila', (SELECT id FROM pgx_drug_classes WHERE code='onco' LIMIT 1), 'Flusan®, Neugrast®, Fauldfluor®', 'O 5-fluorouracil (5-FU) é um quimioterápico fluoropirimidina utilizado para cânceres GI, mama, cabeça/pescoço. A DPD (DPYD) inativa o 5-FU. Deficiência causa toxicidade FATAL. O CPIC EXIGE teste de DPYD antes do uso.', 'DPYD rs3918290 (*2A) CC + rs67376798 (D949V) TT = DPYD NORMAL. 5-FU pode ser usado com segurança do ponto de vista da DPD.', 'rs3918290', '1', 'DPYD', 'Europeia', 'DPYD:\n- rs3918290: CC = Normal\n- rs67376798: TT = Normal\n\nDPYD Normal → 5-FU seguro', 'DPYD normal. 5-FU/fluorouracila pode ser usado conforme protocolo oncológico. NOTA DE CAUTELA: Confirmar interpretação de strand com laudo Genera antes de decisão clínica (risco fatal se invertido).', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Fentanil', (SELECT id FROM pgx_drug_classes WHERE code='analgesico' LIMIT 1), 'Fentanil®, Anesfent®, Fentanest®, Tranil®, Unifental®', 'O fentanil é um opioide sintético potente (100x mais que morfina) utilizado para anestesia, dor crônica (patches) e dor oncológica. NÃO é pró-droga — atua diretamente. É metabolizado pelo CYP3A4. NÃO depende do CYP2D6.', 'CYP3A4 (GG) = NORMAL. OPRM1 (AA) = receptor normal. COMT (AG) = resposta intermediária. rs2952768 (TC) = dose possivelmente maior.', 'rs35599367', '7', 'CYP3A4', 'Europeia', 'CYP3A4: GG = Normal\nOPRM1: AA = Receptor normal\nCOMT: AG = Resposta intermediária\nrs2952768: TC = Heterozigoto\n\nNÃO depende do CYP2D6