-- =============================================
-- MEDIC - Seed de Detalhes de Medicamentos (Lote 10 de N)
-- 10 medicamentos: Midazolam → Meloxicam
-- Pode ser rodado múltiplas vezes com segurança
-- =============================================

SET NAMES utf8mb4;

-- =============================================
-- PARTE A: Inserir medicamentos na pgx_drug_genes
-- =============================================

INSERT IGNORE INTO `pgx_drug_genes` (`drug_name`, `drug_class`, `gene_symbol`, `rsid`, `interaction_type`, `effect_description`, `recommendation_normal`, `recommendation_het`, `recommendation_risk`, `evidence_level`, `source`, `is_active`) VALUES
('Midazolam', 'Hipnóticos/Sedativos', 'CYP3A5', 'rs776746', 'substrate', 'CYP3A5 metaboliza midazolam - expressores eliminam mais rápido', 'Dose padrão (não-expressor)', 'Metabolismo aumentado - pode necessitar dose maior', 'Metabolismo muito aumentado', '2A', 'PharmGKB', 1),
('Metotrexato', 'Imunossupressores/Antineoplásicos', 'MTHFR', 'rs1801133', 'target', 'MTHFR C677T modula toxicidade do metotrexato', 'Dose padrão', 'Toxicidade aumentada - monitorar', 'Toxicidade significativamente aumentada', '2A', 'CPIC', 1),
('Metotrexato', 'Imunossupressores/Antineoplásicos', 'MTRR', 'rs1801394', 'target', 'MTRR A66G modula metabolismo do folato', 'Normal', 'Reciclagem B12 reduzida', 'Muito reduzida', '2B', 'PharmGKB', 1),
('Metoprolol', 'Betabloqueadores', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza metoprolol - lentos têm bradicardia', 'Dose padrão', 'Efeito aumentado', 'Bradicardia/hipotensão - reduzir dose', '1A', 'DPWG', 1),
('Metoclopramida', 'Antieméticos', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza metoclopramida', 'Dose padrão', 'Monitorar EPS', 'Risco de discinesia - reduzir dose', '2B', 'PharmGKB', 1),
('Metilfenidato', 'Psicoestimulantes (TDAH)', 'ADRA2A', 'rs1800544', 'target', 'ADRA2A modula resposta ao metilfenidato', 'Resposta padrão', 'Resposta variável', 'Duração alterada', '2B', 'PharmGKB', 1),
('Metilfenidato', 'Psicoestimulantes (TDAH)', 'SLC6A2', 'rs5569', 'target', 'SLC6A2 (NET) modula recaptação de noradrenalina', 'Normal', 'Transportador com variante', 'Resposta variável', '3', 'PharmGKB', 1),
('Metilfenidato', 'Psicoestimulantes (TDAH)', 'DRD1', 'rs4532', 'target', 'DRD1 modula função executiva e resposta a estimulantes', 'Normal', 'Função executiva variável', 'Função executiva alterada', '3', 'PharmGKB', 1),
('Metadona', 'Analgésicos Opioides', 'COMT', 'rs4680', 'target', 'COMT modula percepção de dor com metadona', 'Dose padrão', 'Pode necessitar dose maior', 'Dose maior', '2A', 'PharmGKB', 1),
('Mercaptopurina', 'Antineoplásicos', 'TPMT', 'rs1800460', 'substrate', 'TPMT metaboliza mercaptopurina - deficiência causa mielossupressão fatal', 'Dose padrão', 'Reduzir dose 30-50%', 'Reduzir dose drasticamente', '1A', 'CPIC', 1),
('Mepivacaína', 'Anestésicos Locais', 'G6PD', 'rs1050829', 'risk', 'G6PD deficiente - risco de metemoglobinemia', 'Sem risco', 'Cautela', 'Monitorar', '3', 'PharmGKB', 1),
('Meperidina', 'Analgésicos Opioides', 'OPRM1', 'rs2952768', 'target', 'rs2952768 associado a dose de opioide pós-operatória', 'Dose padrão', 'Pode necessitar dose maior', 'Dose maior', '3', 'GWAS', 1),
('Meloxicam', 'Anti-inflamatórios (AINEs)', 'CYP2C9', 'rs1799853', 'substrate', 'CYP2C9 metaboliza meloxicam', 'Dose padrão', 'Meia-vida prolongada', 'Risco de sangramento', '2A', 'DPWG', 1);

-- =============================================
-- PARTE B: Detalhes (resumidos para os 10 medicamentos)
-- =============================================

-- 1. MIDAZOLAM
INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Midazolam', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Dormonid®, Dormire®, Dormium®, Induson®', 'O midazolam é um benzodiazepínico de ação ultra-curta utilizado para sedação pré-operatória, indução anestésica e sedação em UTI. É metabolizado pelo CYP3A4 (principal) e CYP3A5. Efeitos adversos incluem depressão respiratória, hipotensão e amnésia anterógrada.', 'CYP3A5 (rs776746 CT) = EXPRESSOR PARCIAL. O midazolam pode ser eliminado mais rapidamente que em não-expressores. CYP3A4 (GG) = normal.', 'rs776746', '7', 'CYP3A5', 'Europeia', 'CYP3A5 rs776746 (*3):\n- GG/AA (não-expressor) = Metabolismo mais lento (duração maior)\n- CT/AG (expressor parcial) = Metabolismo aumentado (duração pode ser menor)\n- CC/TT (expressor) = Metabolismo rápido', 'RELEVANTE PARA CIRURGIA: CYP3A5 expressor parcial (CT). O midazolam pode ter duração MENOR que o esperado. O anestesista pode precisar de doses de manutenção mais frequentes ou dose total maior. Monitorar nível de sedação.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

-- 2. METOTREXATO
INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Metotrexato', (SELECT id FROM pgx_drug_classes WHERE code='imuno_transplante' LIMIT 1), 'Miantrex®, Fauldmetro®, Tecnomet®', 'O metotrexato é um antimetabólito utilizado para artrite reumatoide, psoríase, e quimioterapia. Inibe a diidrofolato redutase. MTHFR e MTRR modulam o metabolismo do folato e a toxicidade. Efeitos adversos incluem mielossupressão, hepatotoxicidade, mucosite, nefrotoxicidade e pneumonite.', 'MTHFR rs1801133 (C677T): GG = NORMAL. rs1801131 (A1298C): TG = HETEROZIGOTO para variante. MTRR rs1801394 (A66G): AG = reciclagem de B12 REDUZIDA. A combinação sugere metabolismo do folato PARCIALMENTE comprometido — pode ter toxicidade levemente aumentada ao metotrexato.', 'rs1801133', '1', 'MTHFR', 'Europeia', 'MTHFR rs1801133 (C677T): GG = Normal (100% atividade)\nMTHFR rs1801131 (A1298C): TG/AC = Heterozigoto (atividade levemente reduzida)\nMTRR rs1801394 (A66G): AG = Reciclagem B12 reduzida\n\nCombinação: Metabolismo do folato parcialmente comprometido', 'MTHFR 677 normal MAS 1298 heterozigoto + MTRR AG. Suplementação de ácido fólico/L-metilfolato é ESSENCIAL durante uso de metotrexato. Monitorar hemograma e função hepática rigorosamente. A toxicidade pode ser levemente maior que em pacientes sem variantes.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

-- 3. METOPROLOL
INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Metoprolol', (SELECT id FROM pgx_drug_classes WHERE code='cardio' LIMIT 1), 'Selozok®, Emprol®, Inephoros®, Minola®, Taxelina®, Zarmine®', 'O metoprolol é um betabloqueador seletivo beta-1 utilizado para hipertensão, angina, ICC e pós-IAM. É metabolizado pelo CYP2D6. Em metabolizadores lentos, concentrações 3-5x maiores com bradicardia e hipotensão. O DPWG recomenda redução de dose. Efeitos adversos incluem bradicardia, hipotensão, fadiga, broncoespasmo e depressão.', 'CYP2D6 (rs3892097) N/D. O DPWG recomenda redução de dose significativa em metabolizadores lentos pelo risco de bradicardia grave.', 'rs3892097', '22', 'CYP2D6', 'Europeia', 'CYP2D6 rs3892097 (*4):\n- GG = Normal\n- GA = Intermediário (monitorar FC)\n- AA = Metabolizador lento → Reduzir dose 50% ou usar atenolol/bisoprolol', 'CYP2D6 indeterminado. Se metoprolol prescrito, monitorar FC e PA rigorosamente. Alternativas menos dependentes do CYP2D6: bisoprolol, atenolol, nebivolol.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

-- 4. METOCLOPRAMIDA
INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Metoclopramida', (SELECT id FROM pgx_drug_classes WHERE code='gastro' LIMIT 1), 'Plasil®, Fluccil®, Naumetron®, Plagex®, Plavom®', 'A metoclopramida é um antiemético e procinético utilizado para náuseas, vômitos e gastroparesia. Atua como antagonista D2 e agonista 5-HT4. É metabolizada pelo CYP2D6. Em metabolizadores lentos, maior risco de efeitos extrapiramidais. Efeitos adversos incluem EPS, discinesia tardia (uso prolongado), sedação e hiperprolactinemia.', 'CYP2D6 (rs3892097) N/D. Em metabolizadores lentos, maior risco de discinesia.', 'rs3892097', '22', 'CYP2D6', 'Europeia', 'CYP2D6: N/D. Metoclopramida metabolizada pelo CYP2D6.', 'CYP2D6 indeterminado. Para antiemético na cirurgia, PREFERIR ONDANSETRONA. Se usar metoclopramida, monitorar sinais extrapiramidais.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

-- 5. METILFENIDATO
INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Metilfenidato', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Ritalina®, Tedeaga®, Attenze®, Consiv®, Concerta®', 'O metilfenidato é um psicoestimulante de primeira linha para TDAH. Atua bloqueando o transportador de dopamina e noradrenalina. NÃO é metabolizado pelo CYP2D6 (metabolizado por esterases). ADRA2A, SLC6A2 e DRD1 modulam resposta. Efeitos adversos incluem insônia, redução de apetite, cefaleia, taquicardia e potencial de abuso.', 'ADRA2A (rs1800544) N/D. SLC6A2 (rs5569 GA) = transportador NET com variante — resposta variável ao metilfenidato. DRD1 (rs4532 TT) = variante associada a função executiva ALTERADA — pode responder diferente a estimulantes. NÃO depende do CYP2D6 (vantagem!).', 'rs5569', '16', 'SLC6A2', 'Europeia', 'SLC6A2 rs5569 (A1287G):\n- AA = Normal\n- GA = Transportador NET com variante (resposta variável)\n- GG = Variante homozigoto\n\nDRD1 rs4532 (A-48G):\n- AA = Normal\n- AG = Função executiva variável\n- GG/TT = Função executiva alterada\n\nADRA2A rs1800544: N/D\n\nNota: Metilfenidato NÃO depende do CYP2D6.', 'MUITO RELEVANTE PARA TDAH/AUTISMO: SLC6A2 GA + DRD1 TT sugerem que a resposta ao metilfenidato pode ser VARIÁVEL. Monitorar eficácia cuidadosamente. Se resposta insuficiente, considerar: 1) Ajuste de dose, 2) Formulação diferente (Concerta vs Ritalina LA), 3) Atomoxetina como alternativa (mas depende do CYP2D6 desconhecido), 4) Lisdexanfetamina. Treino de funções executivas recomendado como complemento.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

-- 6. METADONA
INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Metadona', (SELECT id FROM pgx_drug_classes WHERE code='analgesico' LIMIT 1), 'Mytedom®', 'A metadona é um opioide sintético de longa ação utilizado para dor crônica e tratamento de dependência de opioides. Tem meia-vida muito longa e variável (15-60h). NÃO depende criticamente do CYP2D6. Metabolizada pelo CYP2B6, CYP3A4 e CYP2C19. COMT modula resposta. Efeitos adversos incluem prolongamento QTc, depressão respiratória, constipação e dependência.', 'CYP2B6 N/D. COMT (rs4680 AG) = resposta intermediária a opioides. CYP3A4 (GG) = normal. CYP2C19 (CT/*17) = metabolismo rápido pode afetar parcialmente.', 'rs4680', '22', 'COMT', 'Europeia', 'COMT rs4680 e Metadona:\n- AA = Maior sensibilidade à dor, melhor resposta\n- AG = Intermediário\n- GG = Pode necessitar dose maior\n\nCYP2B6: N/D\nCYP3A4: GG = Normal', 'COMT AG = resposta intermediária. Se metadona for necessária para dor crônica, titular cuidadosamente (meia-vida longa e variável!). ECG obrigatório pelo risco de QTc prolongado. NÃO é primeira escolha para dor aguda.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

-- 7. MERCAPTOPURINA
INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Mercaptopurina', (SELECT id FROM pgx_drug_classes WHERE code='onco' LIMIT 1), 'Purinethol®', 'A mercaptopurina (6-MP) é um antimetabólito utilizado para leucemia linfoblástica aguda (manutenção) e doença inflamatória intestinal. É metabolizada pela TPMT. Deficiência de TPMT causa mielossupressão grave/fatal. O CPIC EXIGE teste de TPMT antes de iniciar. Efeitos adversos incluem mielossupressão, hepatotoxicidade, pancreatite e náuseas.', 'TPMT rs1800460 (*3B) CC + rs1800462 (*2) CC = TPMT NORMAL. Dose padrão de mercaptopurina é segura.', 'rs1800460', '6', 'TPMT', 'Europeia', 'TPMT rs1800460 (*3B): CC = Normal\nTPMT rs1800462 (*2): CC = Normal\n\nTPMT Normal → Dose padrão segura', 'TPMT normal (CC em ambos). Dose padrão de mercaptopurina é segura do ponto de vista da TPMT. Monitorar hemograma conforme protocolo.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

-- 8. MEPIVACAÍNA
INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Mepivacaína', (SELECT id FROM pgx_drug_classes WHERE code='analgesico' LIMIT 1), 'Mepivalem®, Mepicain®, Mepisv®', 'A mepivacaína é um anestésico local tipo amida utilizado em odontologia e bloqueios nervosos. Risco teórico de metemoglobinemia em deficientes de G6PD. Efeitos adversos incluem toxicidade cardiovascular/neurológica em doses altas e reações alérgicas (raras).', 'G6PD (rs1050829 TT) = NORMAL. Sem risco de metemoglobinemia.', 'rs1050829', 'X', 'G6PD', 'Europeia', 'G6PD rs1050829: TT = Normal', 'RELEVANTE PARA CIRURGIA MAXILAR: G6PD normal. Mepivacaína pode ser usada com segurança para anestesia local odontológica/maxilofacial. É frequentemente usada em procedimentos odontológicos.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

-- 9. MEPERIDINA
INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Meperidina', (SELECT id FROM pgx_drug_classes WHERE code='analgesico' LIMIT 1), 'Dolantina®, Demerol®', 'A meperidina (petidina) é um opioide sintético utilizado para dor aguda e tremores pós-anestésicos. Tem metabólito neurotóxico (normeperidina) que se acumula com uso repetido. NÃO é primeira escolha para analgesia. Efeitos adversos incluem convulsões (normeperidina), depressão respiratória, náuseas e interação com IMAO (síndrome serotoninérgica fatal).', 'rs2952768 (TC) = heterozigoto para variante associada a doses maiores de opioides pós-operatórios (GWAS, evidência nível 3). COMT AG = resposta intermediária.', 'rs2952768', '1', 'OPRM1', 'Europeia', 'rs2952768: TC = Heterozigoto (pode necessitar dose maior)\nCOMT rs4680: AG = Resposta intermediária', 'Meperidina NÃO é recomendada para uso repetido (metabólito neurotóxico). Para cirurgia maxilar, PREFERIR morfina, oxicodona ou remifentanila. Se usada pontualmente para tremores, dose única é aceitável.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

-- 10. MELOXICAM
INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Meloxicam', (SELECT id FROM pgx_drug_classes WHERE code='analgesico' LIMIT 1), 'Movatec®, Bioflac®, Loxam®, Melocox®, Melovac®', 'O meloxicam é um AINE inibidor preferencial da COX-2, utilizado para osteoartrite, artrite reumatoide e dor aguda. Possui melhor perfil GI que piroxicam. É metabolizado pelo CYP2C9. Efeitos adversos incluem úlcera gástrica (menos que outros AINEs), sangramento, nefrotoxicidade e risco cardiovascular.', 'CYP2C9 (rs1799853 CC) = *1/*1 = Metabolizador NORMAL. Meloxicam processado adequadamente.', 'rs1799853', '10', 'CYP2C9', 'Europeia', 'CYP2C9 rs1799853 (*2):\n- CC = Normal\n- CT = Intermediário (monitorar)\n- TT = Lento (risco de sangramento GI)', 'CYP2C9 normal. Meloxicam pode ser usado em dose padrão. Boa opção como AINE com perfil COX-2 preferencial e menor risco GI que ibuprofeno/naproxeno.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();
