-- =============================================
-- MEDIC - Seed de Detalhes de Medicamentos (Lote 16 de N)
-- 10 medicamentos: Entacapona → Doxepina
-- Pode ser rodado múltiplas vezes com segurança
-- =============================================

SET NAMES utf8mb4;

-- =============================================
-- PARTE A: Inserir medicamentos na pgx_drug_genes
-- =============================================

INSERT IGNORE INTO `pgx_drug_genes` (`drug_name`, `drug_class`, `gene_symbol`, `rsid`, `interaction_type`, `effect_description`, `recommendation_normal`, `recommendation_het`, `recommendation_risk`, `evidence_level`, `source`, `is_active`) VALUES
('Entacapona', 'Inibidores da COMT', 'COMT', 'rs4680', 'target', 'COMT é o alvo da entacapona - genótipo modula benefício', 'Benefício padrão', 'Benefício intermediário', 'Maior benefício (COMT alta inibida)', '2B', 'PharmGKB', 1),
('Eltrombopague', 'Agonistas de Trombopoietina', 'F5', 'rs6025', 'risk', 'Fator V Leiden aumenta risco trombótico com estimuladores de plaquetas', 'Sem risco adicional de trombose', 'Risco trombótico aumentado', 'Alto risco', '2B', 'PharmGKB', 1),
('Eliglustate', 'Agentes para Doença de Gaucher', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza eliglustate - FDA limita em lentos', 'Dose padrão', 'Monitorar', 'Dose máxima 84mg 1x/dia (FDA)', '1A', 'FDA', 1),
('Efavirenz', 'Antivirais (HIV)', 'CYP2B6', 'rs3211371', 'substrate', 'CYP2B6 metaboliza efavirenz - lentos têm mais neurotoxicidade', 'Dose 600mg', 'Monitorar neurotoxicidade', 'Considerar dose 400mg', '1A', 'CPIC', 1),
('Duloxetina', 'Antidepressivos (IRSN)', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza duloxetina parcialmente', 'Dose padrão', 'Monitorar', 'Monitorar efeitos', '2A', 'PharmGKB', 1),
('Dronabinol', 'Canabinoides/Antieméticos', 'CYP2C9', 'rs1799853', 'substrate', 'CYP2C9 metaboliza dronabinol (THC)', 'Dose padrão', 'Efeitos prolongados', 'Efeitos muito prolongados', '2B', 'PharmGKB', 1),
('Doxorrubicina', 'Antineoplásicos (Antraciclinas)', 'RARG', 'rs2229774', 'risk', 'RARG S427L associado a CARDIOTOXICIDADE com antraciclinas', 'Risco padrão', 'RISCO AUMENTADO de cardiotoxicidade', 'Risco muito aumentado', '2A', 'CPGG', 1),
('Doxorrubicina', 'Antineoplásicos (Antraciclinas)', 'SLC28A3', 'rs7853758', 'risk', 'SLC28A3 pode ter efeito PROTETOR contra cardiotoxicidade', 'Sem proteção', 'Proteção parcial', 'Proteção', '2B', 'PharmGKB', 1),
('Doxepina', 'Antidepressivos (Tricíclicos)', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza doxepina - CPIC guideline', 'Dose padrão', 'Monitorar', 'Reduzir dose ou alternativa', '1A', 'CPIC', 1),
('Doxepina', 'Antidepressivos (Tricíclicos)', 'CYP2C19', 'rs12248560', 'substrate', 'CYP2C19 é via secundária - *17 aumenta metabolismo', 'Dose padrão', 'Metabolismo aumentado', 'Pode necessitar dose maior', '2A', 'CPIC', 1);

-- =============================================
-- PARTE B: Detalhes dos medicamentos (principais)
-- =============================================

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Doxorrubicina', (SELECT id FROM pgx_drug_classes WHERE code='onco' LIMIT 1), 'Fauldoxo®, Docks®', 'A doxorrubicina é uma antraciclina utilizada para diversos cânceres (mama, linfomas, sarcomas, leucemias). Seu principal efeito adverso dose-limitante é a CARDIOTOXICIDADE (cardiomiopatia, ICC). O gene RARG (rs2229774) é um marcador de risco de cardiotoxicidade identificado pelo CPGG (Canadian Pharmacogenomics Network).', 'RARG (rs2229774 GA) = HETEROZIGOTO para variante S427L = RISCO AUMENTADO de cardiotoxicidade com antraciclinas. SLC28A3 (rs7853758 GA) = heterozigoto — pode oferecer PROTEÇÃO PARCIAL contra cardiotoxicidade (achado que pode compensar parcialmente o RARG).', 'rs2229774', '12', 'RARG', 'Europeia', 'RARG rs2229774 (S427L):\n- CC = Normal (risco padrão)\n- GA/CT = Heterozigoto → RISCO AUMENTADO de cardiotoxicidade\n- AA/TT = Homozigoto variante → Risco muito aumentado\n\nSLC28A3 rs7853758:\n- GG = Sem proteção\n- GA = Proteção PARCIAL contra cardiotoxicidade\n- AA = Proteção', 'ACHADO IMPORTANTE: RARG GA = risco AUMENTADO de cardiotoxicidade com doxorrubicina/antraciclinas. SLC28A3 GA pode oferecer proteção parcial. Se quimioterapia com antraciclina for necessária: 1) Ecocardiograma de base obrigatório, 2) Monitoramento cardíaco frequente durante tratamento, 3) Considerar cardio-protetor (dexrazoxano), 4) Limite cumulativo de dose ainda mais rigoroso.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Duloxetina', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Cymbalta®, Dulorgran®, Velija®, Cymbi®', 'A duloxetina é um IRSN (inibidor da recaptação de serotonina e noradrenalina) utilizado para depressão, ansiedade generalizada, dor neuropática e fibromialgia. É metabolizada parcialmente pelo CYP2D6, mas tem múltiplas vias (CYP1A2 também). É uma ALTERNATIVA aos ISRS quando estes têm eficácia insuficiente.', 'CYP2D6 (rs3892097) N/D. A duloxetina tem dependência PARCIAL do CYP2D6 (menos que venlafaxina). CYP1A2 (CA = ultra-rápido) pode aumentar parcialmente o metabolismo. É ALTERNATIVA aos ISRS dado que HTR1A CG reduz resposta a ISRS em 30%.', 'rs3892097', '22', 'CYP2D6', 'Europeia', 'CYP2D6: N/D (dependência parcial)\nCYP1A2: CA = Ultra-rápido (via parcial)\n\nNota: Duloxetina é IRSN (não ISRS) — pode ser alternativa se ISRS insuficiente.', 'RELEVANTE PARA AUTISMO/ANSIEDADE: A duloxetina é ALTERNATIVA aos ISRS (escitalopram/sertralina) quando estes são insuficientes. HTR1A CG reduz resposta a ISRS em -30%, mas este efeito é MENOS relevante para IRSN (que também atuam na noradrenalina). CYP2D6 parcial — impacto menor. CYP1A2 ultra-rápido pode contribuir. Boa opção para dor neuropática + depressão/ansiedade.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Entacapona', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Comtan®, Capinson®, Capona®, Entapark®, Entarkin®', 'A entacapona é um inibidor periférico da COMT, usada como adjuvante à levodopa no Parkinson. Bloqueia a degradação da dopamina pela COMT, prolongando o efeito da levodopa.', 'COMT (rs4680 AG = Val/Met) = atividade INTERMEDIÁRIA. A entacapona bloqueia a COMT — pacientes com COMT intermediária/alta se beneficiam mais do que aqueles com COMT já baixa (Met/Met).', 'rs4680', '22', 'COMT', 'Europeia', 'COMT rs4680 e Entacapona:\n- AA (Met/Met) = COMT já baixa → Menor benefício adicional\n- AG (Val/Met) = Benefício intermediário\n- GG (Val/Val) = COMT alta → MAIOR benefício da entacapona', 'COMT AG = benefício intermediário da entacapona. Se wearing-off de levodopa for problema, entacapona é opção racional.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();