-- =============================================
-- MEDIC - Seed de Detalhes de Medicamentos (Lote 17 de N)
-- 10 medicamentos: Donepezila → Deutetrabenazina
-- Pode ser rodado múltiplas vezes com segurança
-- =============================================

SET NAMES utf8mb4;

-- =============================================
-- PARTE A: Inserir medicamentos na pgx_drug_genes
-- =============================================

INSERT IGNORE INTO `pgx_drug_genes` (`drug_name`, `drug_class`, `gene_symbol`, `rsid`, `interaction_type`, `effect_description`, `recommendation_normal`, `recommendation_het`, `recommendation_risk`, `evidence_level`, `source`, `is_active`) VALUES
('Donepezila', 'Inibidores da Colinesterase', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza donepezila', 'Dose padrão', 'Monitorar efeitos colinérgicos', 'Dose menor', '2B', 'PharmGKB', 1),
('Divalproato de Sódio', 'Anticonvulsivantes/Estabilizadores', 'ANKK1', 'rs1800497', 'target', 'ANKK1/DRD2 TaqIA modula resposta', 'Resposta padrão', 'Resposta variável', 'Resposta variável', '3', 'PharmGKB', 1),
('Diltiazem', 'Bloqueadores de Canais de Cálcio', 'PLCD3', 'rs12946454', 'target', 'PLCD3 modula resposta pressórica', 'Resposta padrão', 'Resposta variável', 'Resposta variável', '3', 'PharmGKB', 1),
('Digoxina', 'Glicosídeos Cardíacos', 'ABCB1', 'rs1045642', 'transporter', 'ABCB1 modula níveis de digoxina', 'Níveis padrão', 'Níveis variáveis', 'Níveis potencialmente maiores', '2B', 'PharmGKB', 1),
('Diclofenaco', 'Anti-inflamatórios (AINEs)', 'CYP2C9', 'rs1799853', 'substrate', 'CYP2C9 metaboliza diclofenaco', 'Dose padrão', 'Meia-vida prolongada', 'Risco de sangramento/nefrotoxicidade', '2A', 'DPWG', 1),
('Diazepam', 'Ansiolíticos (Benzodiazepínicos)', 'CYP2C19', 'rs12248560', 'substrate', 'CYP2C19 metaboliza diazepam - *17 elimina mais rápido', 'Dose padrão', 'Duração pode ser menor', 'Duração reduzida', '2A', 'PharmGKB', 1),
('Diazepam', 'Ansiolíticos (Benzodiazepínicos)', 'CYP3A4', 'rs35599367', 'substrate', 'CYP3A4 é via secundária', 'Normal', 'Metabolismo reduzido', 'Monitorar', '3', 'PharmGKB', 1),
('Dextroanfetamina', 'Psicoestimulantes (TDAH)', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza parcialmente anfetamina', 'Dose padrão', 'Monitorar', 'Monitorar', '3', 'PharmGKB', 1),
('Dextroanfetamina', 'Psicoestimulantes (TDAH)', 'DRD1', 'rs4532', 'target', 'DRD1 modula resposta a estimulantes', 'Normal', 'Função executiva variável', 'Função executiva alterada', '3', 'PharmGKB', 1),
('Dexmetilfenidato', 'Psicoestimulantes (TDAH)', 'ADRA2A', 'rs1800544', 'target', 'ADRA2A modula resposta', 'Resposta padrão', 'Resposta variável', 'Duração alterada', '2B', 'PharmGKB', 1),
('Dexlansoprazol', 'IBPs (Inibidores de Bomba de Prótons)', 'CYP2C19', 'rs12248560', 'substrate', 'CYP2C19 metaboliza dexlansoprazol', 'Dose padrão', 'Eficácia reduzida', 'Considerar rabeprazol', '2A', 'CPIC', 1),
('Deutetrabenazina', 'Inibidores do Transportador de Monoamina', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza deutetrabenazina - FDA limita dose em lentos', 'Dose padrão', 'Monitorar', 'Dose máxima limitada (FDA)', '1A', 'FDA', 1);

-- =============================================
-- PARTE B: Detalhes (principais)
-- =============================================

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Diazepam', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Valium®, Compaz®, Uni-diazepax®', 'O diazepam é um benzodiazepínico de longa ação utilizado para ansiedade, convulsões, espasmo muscular e sedação. É metabolizado pelo CYP2C19 (via principal) e CYP3A4 (secundária). Em metabolizadores rápidos do CYP2C19, a duração pode ser MENOR.', 'CYP2C19 *1/*17 (CT) = METABOLIZADOR RÁPIDO. O diazepam pode ser eliminado mais rapidamente, com duração de ação potencialmente MENOR. CYP3A4 (GG) = normal.', 'rs12248560', '10', 'CYP2C19', 'Europeia', 'CYP2C19 e Diazepam:\n- *1/*1 = Normal\n- *1/*17 = Metabolismo aumentado (duração pode ser menor)\n- *17/*17 = Duração significativamente menor\n- *2/*2 = Lento (duração prolongada)', 'CYP2C19 rápido (*1/*17). Diazepam pode ter duração MENOR que esperado. Se for necessário benzodiazepínico, considerar: 1) Dose mais frequente, 2) Lorazepam como alternativa (NÃO depende de CYP), 3) Oxazepam (NÃO depende de CYP). Para sedação na cirurgia, midazolam + monitoramento (CYP3A5 expressor parcial reduz duração também).', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Diclofenaco', (SELECT id FROM pgx_drug_classes WHERE code='analgesico' LIMIT 1), 'Voltaren®, Belfaren®, Fenaren®, Biofenac®, Voltaflex®', 'O diclofenaco é um AINE potente utilizado para dor, inflamação e artrite. É metabolizado pelo CYP2C9. Em metabolizadores lentos, risco de sangramento e nefrotoxicidade.', 'CYP2C9 (CC = *1/*1) = Metabolizador NORMAL. Diclofenaco processado adequadamente.', 'rs1799853', '10', 'CYP2C9', 'Europeia', 'CYP2C9 e Diclofenaco:\n- CC = Normal\n- CT = Intermediário (monitorar)\n- TT = Lento (risco)', 'CYP2C9 normal. Diclofenaco dose padrão. Pode ser opção anti-inflamatória para dor pós-operatória se AINEs forem indicados.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Dexlansoprazol', (SELECT id FROM pgx_drug_classes WHERE code='gastro' LIMIT 1), 'Dexilant®, Kapidex®', 'O dexlansoprazol é o enantiômero R do lansoprazol com liberação dupla. Dependente do CYP2C19 (como lansoprazol).', 'CYP2C19 *1/*17 = metabolizador rápido. Eficácia possivelmente reduzida. Preferir rabeprazol.', 'rs12248560', '10', 'CYP2C19', 'Europeia', 'CYP2C19 e Dexlansoprazol:\n- Similar ao lansoprazol em dependência do CYP2C19\n- *1/*17 = Eficácia reduzida', 'CYP2C19 rápido. Dexlansoprazol pode ter eficácia reduzida. PREFERIR RABEPRAZOL.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Dexmetilfenidato', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Ritalina LA®, Focalin®', 'O dexmetilfenidato é o enantiômero D do metilfenidato, mais ativo. NÃO depende do CYP2D6 (metabolizado por esterases). ADRA2A modula resposta.', 'ADRA2A (rs1800544) N/D. Mesma análise do metilfenidato — SLC6A2 GA + DRD1 TT = resposta VARIÁVEL. NÃO depende do CYP2D6.', 'rs1800544', '10', 'ADRA2A', 'Europeia', 'ADRA2A: N/D\nSLC6A2 rs5569: GA = Variável\nDRD1 rs4532: TT = Função executiva alterada\n\nNÃO depende de CYP2D6.', 'Mesma recomendação do metilfenidato: resposta variável, monitorar eficácia. NÃO depende do CYP2D6 (vantagem). Ritalina LA é formulação de liberação prolongada do metilfenidato (contém D e L).', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();