-- =============================================
-- MEDIC - Seed de Detalhes de Medicamentos (Lote 11 de N)
-- 10 medicamentos: Maraviroque → Lidocaína/Prilocaína
-- Pode ser rodado múltiplas vezes com segurança
-- =============================================

SET NAMES utf8mb4;

-- =============================================
-- PARTE A: Inserir medicamentos na pgx_drug_genes
-- =============================================

INSERT IGNORE INTO `pgx_drug_genes` (`drug_name`, `drug_class`, `gene_symbol`, `rsid`, `interaction_type`, `effect_description`, `recommendation_normal`, `recommendation_het`, `recommendation_risk`, `evidence_level`, `source`, `is_active`) VALUES
('Maraviroque', 'Antivirais (HIV)', 'CYP3A5', 'rs776746', 'substrate', 'CYP3A5 metaboliza maraviroque - expressores eliminam mais rápido', 'Dose padrão', 'Metabolismo aumentado', 'Pode necessitar dose maior', '2B', 'PharmGKB', 1),
('Mafenida', 'Antibióticos (Sulfonamidas tópicas)', 'G6PD', 'rs1050829', 'risk', 'G6PD deficiente - risco de hemólise com sulfonamidas', 'Sem risco', 'Cautela', 'Monitorar', '3', 'PharmGKB', 1),
('Lurasidona', 'Antipsicóticos', 'CYP3A4', 'rs35599367', 'substrate', 'CYP3A4 metaboliza lurasidona', 'Dose padrão', 'Metabolismo reduzido', 'Risco de acúmulo', '2A', 'PharmGKB', 1),
('Lovastatina', 'Estatinas', 'SLCO1B1', 'rs4149056', 'transporter', 'SLCO1B1 transporta lovastatina - risco de miopatia', 'Dose padrão', 'Dose máxima limitada', 'Risco de miopatia', '1A', 'CPIC', 1),
('Losartana', 'Antagonistas de Angiotensina II (BRAs)', 'CYP2C9', 'rs1799853', 'substrate', 'CYP2C9 converte losartana em metabólito ativo (E-3174)', 'Dose padrão (boa conversão)', 'Conversão intermediária', 'Conversão reduzida - eficácia pode ser menor', '2A', 'PharmGKB', 1),
('Losartana', 'Antagonistas de Angiotensina II (BRAs)', 'CYP3A4', 'rs35599367', 'substrate', 'CYP3A4 é via secundária', 'Normal', 'Metabolismo reduzido', 'Monitorar', '3', 'PharmGKB', 1),
('Lorazepam', 'Ansiolíticos (Benzodiazepínicos)', 'UGT2B15', 'rs1902023', 'substrate', 'UGT2B15 metaboliza lorazepam por glucuronidação - NÃO depende CYP', 'Dose padrão', 'Metabolismo reduzido', 'Meia-vida prolongada', '2B', 'PharmGKB', 1),
('Lítio', 'Estabilizadores de Humor', 'GSK3B', 'rs6438552', 'target', 'GSK3B modula resposta ao lítio', 'Resposta padrão', 'Resposta variável', 'Resposta variável', '3', 'PharmGKB', 1),
('Lisdexanfetamina', 'Psicoestimulantes (TDAH)', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza parcialmente anfetamina', 'Dose padrão', 'Monitorar', 'Monitorar', '3', 'PharmGKB', 1),
('Lisdexanfetamina', 'Psicoestimulantes (TDAH)', 'DRD1', 'rs4532', 'target', 'DRD1 modula resposta a estimulantes', 'Normal', 'Função executiva variável', 'Função executiva alterada', '3', 'PharmGKB', 1),
('Lidocaína-Tetracaína', 'Anestésicos Locais', 'G6PD', 'rs1050829', 'risk', 'G6PD deficiente - risco teórico de metemoglobinemia', 'Sem risco', 'Cautela', 'Monitorar', '3', 'PharmGKB', 1),
('Lidocaína-Prilocaína', 'Anestésicos Locais', 'G6PD', 'rs1050829', 'risk', 'G6PD deficiente - prilocaína é o principal causador de metemoglobinemia', 'Sem risco', 'Cautela', 'Monitorar metemoglobina', '2B', 'PharmGKB', 1);

-- =============================================
-- PARTE B: Detalhes dos medicamentos
-- =============================================

-- 1. MARAVIROQUE
INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Maraviroque', (SELECT id FROM pgx_drug_classes WHERE code='infecto' LIMIT 1), 'Celsentri®', 'O maraviroque é um antirretroviral antagonista do receptor CCR5, utilizado para HIV-1 com tropismo CCR5. É metabolizado pelo CYP3A4/CYP3A5. Efeitos adversos incluem hepatotoxicidade, tosse, febre e infecções do trato respiratório.', 'CYP3A5 (rs776746 CT) = EXPRESSOR PARCIAL. O maraviroque pode ser eliminado mais rapidamente. CYP3A4 (GG) = normal.', 'rs776746', '7', 'CYP3A5', 'Europeia', 'CYP3A5 rs776746: CT = Expressor parcial (metabolismo aumentado)\nCYP3A4: GG = Normal', 'CYP3A5 expressor parcial. Maraviroque pode ter níveis levemente menores. Monitorar carga viral conforme protocolo HIV. Interações com inibidores/indutores do CYP3A são frequentes na terapia HIV.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

-- 2. MAFENIDA
INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Mafenida', (SELECT id FROM pgx_drug_classes WHERE code='infecto' LIMIT 1), 'Sulfamaf®', 'A mafenida é um antibiótico sulfonamida tópico utilizado para prevenção de infecção em queimaduras. Por ser sulfonamida, pode causar hemólise em deficientes de G6PD. Efeitos adversos incluem dor local, acidose metabólica (absorção sistêmica) e reações alérgicas.', 'G6PD (rs1050829 TT) = NORMAL. Sem risco de hemólise.', 'rs1050829', 'X', 'G6PD', 'Europeia', 'G6PD rs1050829: TT = Normal', 'G6PD normal. Mafenida pode ser usada topicamente com segurança.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

-- 3. LURASIDONA
INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Lurasidona', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Latuda®, Lutab®', 'A lurasidona é um antipsicótico atípico com perfil metabólico favorável (baixo ganho de peso). Indicada para esquizofrenia e depressão bipolar. É metabolizada pelo CYP3A4. CONTRAINDICADA com inibidores/indutores potentes do CYP3A4. Efeitos adversos incluem acatisia, sonolência, náuseas e EPS.', 'CYP3A4 (rs35599367 GG) = metabolismo NORMAL. Lurasidona processada adequadamente.', 'rs35599367', '7', 'CYP3A4', 'Europeia', 'CYP3A4 rs35599367 (*22): GG = Normal', 'CYP3A4 normal. Lurasidona em dose padrão. Perfil metabólico favorável para autistas (baixo ganho de peso comparado a olanzapina/quetiapina). DEVE ser tomada com alimento (≥350kcal) para absorção adequada.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

-- 4. LOVASTATINA
INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Lovastatina', (SELECT id FROM pgx_drug_classes WHERE code='cardio' LIMIT 1), 'Lovastatina®, Lovaton®, Lovax®, Redustatin®', 'A lovastatina é uma estatina pró-droga metabolizada pelo CYP3A4 e transportada pelo SLCO1B1. Similar à sinvastatina em termos de risco farmacogenético. Efeitos adversos incluem miopatia (dose-dependente), hepatotoxicidade e rabdomiólise.', 'SLCO1B1 (rs4149056 TC) = transportador REDUZIDO. Mesmo impacto que na sinvastatina — risco aumentado de miopatia.', 'rs4149056', '12', 'SLCO1B1', 'Europeia', 'SLCO1B1 rs4149056 para Lovastatina:\n- TT = Normal\n- TC = Risco aumentado de miopatia (similar à sinvastatina)\n- CC = Risco alto', 'SLCO1B1 TC. Lovastatina tem risco similar à sinvastatina. PREFERIR rosuvastatina ou pravastatina que são menos afetadas pelo SLCO1B1.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

-- 5. LOSARTANA
INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Losartana', (SELECT id FROM pgx_drug_classes WHERE code='cardio' LIMIT 1), 'Cozaar®, Zart®, Zaarpress®, Lotanol®, Torlós®, Valtrian®', 'A losartana é um BRA (bloqueador do receptor de angiotensina II) utilizado para hipertensão, nefropatia diabética e ICC. É uma PRÓ-DROGA convertida pelo CYP2C9 em seu metabólito ativo (E-3174, 10-40x mais potente). Em metabolizadores lentos do CYP2C9, a conversão é reduzida com menor eficácia anti-hipertensiva. Efeitos adversos incluem hipotensão, hipercalemia, tontura e angioedema (raro).', 'CYP2C9 (rs1799853 CC) = *1/*1 = Metabolizador NORMAL. A losartana é convertida adequadamente em seu metabólito ativo. CYP3A4 (GG) = normal.', 'rs1799853', '10', 'CYP2C9', 'Europeia', 'CYP2C9 rs1799853 (*2) e Losartana:\n- CC = Normal (boa conversão em metabólito ativo)\n- CT = Intermediário (conversão parcial - monitorar PA)\n- TT = Lento (conversão reduzida -