-- =============================================
-- MEDIC - Seed de Detalhes de Medicamentos (Lote 15 de N)
-- 10 medicamentos: Fenobarbital → Erdafitinibe
-- Pode ser rodado múltiplas vezes com segurança
-- =============================================

SET NAMES utf8mb4;

-- =============================================
-- PARTE A: Inserir medicamentos na pgx_drug_genes
-- =============================================

INSERT IGNORE INTO `pgx_drug_genes` (`drug_name`, `drug_class`, `gene_symbol`, `rsid`, `interaction_type`, `effect_description`, `recommendation_normal`, `recommendation_het`, `recommendation_risk`, `evidence_level`, `source`, `is_active`) VALUES
('Fenobarbital', 'Anticonvulsivantes', 'ABCB1', 'rs1045642', 'transporter', 'ABCB1 modula níveis de fenobarbital no SNC', 'Normal', 'Níveis variáveis', 'Níveis potencialmente maiores no SNC', '3', 'PharmGKB', 1),
('Fenitoína', 'Anticonvulsivantes', 'CYP2C9', 'rs1799853', 'substrate', 'CYP2C9 metaboliza fenitoína - CPIC guideline', 'Dose padrão', 'Reduzir dose 25%', 'Reduzir dose 50%', '1A', 'CPIC', 1),
('Fenitoína', 'Anticonvulsivantes', 'HLA-B', 'rs3909184', 'risk', 'HLA-B*15:02 - SJS em asiáticos', 'Sem risco (europeus)', 'Baixo risco', 'Tipagem HLA', '1A', 'CPIC', 1),
('Femprocumona', 'Anticoagulantes', 'VKORC1', 'rs9923231', 'target', 'VKORC1 modula sensibilidade a cumarínicos', 'Dose padrão', 'Sensível - dose menor', 'Muito sensível - dose muito menor', '1A', 'CPIC', 1),
('Femprocumona', 'Anticoagulantes', 'CYP4F2', 'rs2108622', 'substrate', 'CYP4F2 afeta metabolismo vitamina K', 'Normal', 'Metabolismo VitK reduzido', 'Muito reduzido', '2A', 'PharmGKB', 1),
('Extrato de Cannabis', 'Canabinoides', 'CYP3A4', 'rs35599367', 'substrate', 'CYP3A4 metaboliza canabinoides', 'Normal', 'Metabolismo reduzido', 'Acúmulo', '3', 'PharmGKB', 1),
('Exemestano', 'Antineoplásicos (Inibidores de Aromatase)', 'CYP3A4', 'rs35599367', 'substrate', 'CYP3A4 metaboliza exemestano', 'Dose padrão', 'Metabolismo reduzido', 'Monitorar', '2B', 'PharmGKB', 1),
('Eszopiclona', 'Hipnóticos', 'CYP3A4', 'rs35599367', 'substrate', 'CYP3A4 metaboliza eszopiclona', 'Dose padrão', 'Metabolismo reduzido', 'Sedação prolongada', '2A', 'PharmGKB', 1),
('Esomeprazol', 'IBPs (Inibidores de Bomba de Prótons)', 'CYP2C19', 'rs12248560', 'substrate', 'CYP2C19 metaboliza esomeprazol - moderadamente dependente', 'Dose padrão', 'Eficácia moderadamente reduzida', 'Considerar rabeprazol', '2A', 'CPIC', 1),
('Escitalopram', 'Antidepressivos (ISRS)', 'CYP2C19', 'rs12248560', 'substrate', 'CYP2C19*17 aumenta metabolismo do escitalopram', 'Dose padrão', 'Níveis 30-40% menores', 'Níveis muito reduzidos - alternativa', '1A', 'CPIC', 1),
('Escitalopram', 'Antidepressivos (ISRS)', 'HTR2A', 'rs6311', 'target', 'HTR2A modula resposta a ISRS', 'Normal', 'Resposta variável', 'Resposta variável', '2B', 'PharmGKB', 1),
('Escitalopram', 'Antidepressivos (ISRS)', 'GRIK4', 'rs1954787', 'target', 'GRIK4 associado a resposta a ISRS (STAR*D)', 'Resposta padrão', 'Possivelmente melhor resposta', 'Possivelmente melhor resposta', '3', 'PharmGKB', 1),
('Escitalopram', 'Antidepressivos (ISRS)', 'COMT', 'rs4680', 'target', 'COMT modula neurotransmissão dopaminérgica', 'Normal', 'Intermediário', 'Variável', '3', 'PharmGKB', 1),
('Eritromicina-Sulfisoxazol', 'Antibióticos', 'G6PD', 'rs1050829', 'risk', 'G6PD deficiente - sulfisoxazol pode causar hemólise', 'Sem risco', 'Cautela', 'Monitorar', '2A', 'CPIC', 1),
('Erdafitinibe', 'Antineoplásicos', 'CYP2C9', 'rs1799853', 'substrate', 'CYP2C9 metaboliza erdafitinibe', 'Dose padrão', 'Monitorar', 'Monitorar', '2B', 'PharmGKB', 1);

-- =============================================
-- PARTE B: Detalhes dos medicamentos (principais)
-- =============================================

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Escitalopram', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Lexapro®, Deciprax®, Esc®, Escilex®, Exodus®', 'O escitalopram é o enantiômero S da citalopram, considerado o ISRS mais seletivo. Indicado para depressão, ansiedade generalizada e TOC. É metabolizado pelo CYP2C19 (via principal). O CPIC tem guideline: metabolizadores rápidos *1/*17 têm níveis 30-40% menores. HTR2A, GRIK4, FKBP5 e COMT modulam resposta.', 'CYP2C19 *1/*17 (CT) = METABOLIZADOR RÁPIDO — níveis 30-40% MENORES. HTR2A (rs6311 TT) = variante homozigoto. GRIK4 (rs1954787 TC) = heterozigoto (associado a melhor resposta em STAR*D). FKBP5 (CC) = normal. COMT (AG) = intermediário.', 'rs12248560', '10', 'CYP2C19', 'Europeia', 'CYP2C19 e Escitalopram (CPIC guideline):\n- *1/*1 = Normal → Dose padrão (10-20mg)\n- *1/*17 = Metabolizador rápido → Níveis 30-40% menores. CPIC: considerar dose maior ou alternativa\n- *17/*17 = Ultra-rápido → Alternativa recomendada\n- *2/*2 = Lento → Reduzir dose 50%\n\nHTR2A rs6311: TT = Variante (resposta variável)\nGRIK4 rs1954787: TC = Heterozigoto (STAR*D: possível boa resposta)\nFKBP5: CC = Favorável\nCOMT: AG = Intermediário', 'MUITO RELEVANTE PARA AUTISMO/ANSIEDADE: CYP2C19 *1/*17 = níveis 30-40% menores. Mesmo problema da sertralina. PORÉM GRIK4 TC é achado favorável (STAR*D mostrou melhor resposta). Se escitalopram for prescrito: 1) Considerar dose na faixa superior (15-20mg), 2) Monitorar resposta nas primeiras semanas, 3) HTR1A CG (-30% ISRS) se aplica ao escitalopram também. Alternativa se insuficiente: IRSN (duloxetina/venlafaxina).', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Femprocumona', (SELECT id FROM pgx_drug_classes WHERE code='cardio' LIMIT 1), 'Marcoumar®', 'A femprocumona é um anticoagulante cumarínico (similar à varfarina) utilizado para prevenção de tromboembolismo. Como a varfarina, é afetada pelo VKORC1 e CYP4F2. O mesmo achado de VKORC1 TT se aplica.', 'VKORC1 (rs9923231 TT) = MUITO SENSÍVEL (mesmo que varfarina). CYP4F2 (rs2108622 CT) = metabolismo intermediário da vitamina K.', 'rs9923231', '16', 'VKORC1', 'Europeia', 'VKORC1 rs9923231: TT = Muito sensível a cumarínicos\nCYP4F2 rs2108622: CT = Intermediário\n\nMesmo perfil que varfarina!', 'VKORC1 TT = MUITO SENSÍVEL. Femprocumona (como varfarina) requer dose significativamente reduzida. PREFERIR DOACs (rivaroxabana, apixabana) se anticoagulação necessária.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Fenitoína', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Hidantal®, Dantalin®, Fenital®, Unifenitoin®', 'A fenitoína é um anticonvulsivante clássico utilizado para epilepsia e neuralgia do trigêmeo. É metabolizada pelo CYP2C9 (principal) e CYP2C19. O CPIC tem guideline específico. HLA-B*15:02 é risco de SJS em asiáticos.', 'CYP2C9 (CC) = *1/*1 = NORMAL. Fenitoína dose padrão. HLA-B*15:02 proxy GG = provavelmente negativo (europeu).', 'rs1799853', '10', 'CYP2C9', 'Europeia', 'CYP2C9 e Fenitoína (CPIC):\n- *1/*1 = Normal\n- *1/*2 = Intermediário (monitorar níveis)\n- *1/*3 = Lento (reduzir 25%)\n- *3/*3 = Muito lento (reduzir 50%)\n\nHLA-B: Risco SJS baixo em europeus', 'CYP2C9 normal. Fenitoína dose padrão com monitoramento de níveis séricos (10-20 mcg/mL). Risco SJS baixo.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Esomeprazol', (SELECT id FROM pgx_drug_classes WHERE code='gastro' LIMIT 1), 'Nexium®, Ésio®, Esmog®, Esogastro®, Esoneo®, Gaeso®', 'O esomeprazol é o enantiômero S do omeprazol. É moderadamente dependente do CYP2C19 — menos que omepraz