-- =============================================
-- MEDIC - Seed de Detalhes de Medicamentos (Lote 13 de N)
-- 10 medicamentos: Hidrocodona → Furosemida
-- Pode ser rodado múltiplas vezes com segurança
-- =============================================

SET NAMES utf8mb4;

-- =============================================
-- PARTE A: Inserir medicamentos na pgx_drug_genes
-- =============================================

INSERT IGNORE INTO `pgx_drug_genes` (`drug_name`, `drug_class`, `gene_symbol`, `rsid`, `interaction_type`, `effect_description`, `recommendation_normal`, `recommendation_het`, `recommendation_risk`, `evidence_level`, `source`, `is_active`) VALUES
('Hidrocodona', 'Analgésicos Opioides', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 converte hidrocodona em hidromorfona - pró-droga parcial', 'Dose padrão', 'Analgesia possivelmente reduzida', 'Eficácia reduzida em metabolizadores nulos', '2A', 'CPIC', 1),
('Hidroclorotiazida', 'Diuréticos', 'NEDD4L', 'rs4149601', 'target', 'NEDD4L modula resposta pressórica a tiazídicos', 'Resposta padrão', 'Resposta variável', 'Resposta variável', '3', 'PharmGKB', 1),
('Hidroclorotiazida', 'Diuréticos', 'ADD1', 'rs4961', 'target', 'ADD1 G460W modula sensibilidade ao sódio e resposta a tiazídicos', 'Resposta padrão', 'Sensibilidade ao sódio intermediária', 'Alta sensibilidade ao sódio', '2B', 'PharmGKB', 1),
('Haloperidol', 'Antipsicóticos', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza haloperidol', 'Dose padrão', 'Efeito aumentado', 'Risco de EPS - reduzir dose', '1A', 'DPWG', 1),
('Haloperidol', 'Antipsicóticos', 'MC4R', 'rs17782313', 'risk', 'MC4R modula ganho de peso', 'Sem risco aumentado', 'Risco moderado', 'Risco alto', '2B', 'PharmGKB', 1),
('Guanfacina', 'Não estimulantes SNC (TDAH)', 'CYP3A4', 'rs35599367', 'substrate', 'CYP3A4 metaboliza guanfacina', 'Dose padrão', 'Metabolismo reduzido', 'Risco de acúmulo', '2A', 'PharmGKB', 1),
('Glimepirida', 'Antidiabéticos (Sulfonilureias)', 'G6PD', 'rs1050829', 'risk', 'G6PD deficiente - sulfonilureias podem causar hemólise', 'Sem risco', 'Cautela', 'Monitorar', '3', 'PharmGKB', 1),
('Gliclazida', 'Antidiabéticos (Sulfonilureias)', 'G6PD', 'rs1050829', 'risk', 'G6PD deficiente - risco de hemólise', 'Sem risco', 'Cautela', 'Monitorar', '3', 'PharmGKB', 1),
('Glibenclamida', 'Antidiabéticos (Sulfonilureias)', 'G6PD', 'rs1050829', 'risk', 'G6PD deficiente - risco de hemólise', 'Sem risco', 'Cautela', 'Monitorar', '3', 'PharmGKB', 1),
('Gefitinibe', 'Antineoplásicos (Inibidores TK)', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza parcialmente gefitinibe', 'Dose padrão', 'Monitorar', 'Monitorar', '3', 'PharmGKB', 1),
('Galantamina', 'Inibidores da Colinesterase', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza galantamina', 'Dose padrão', 'Monitorar efeitos colinérgicos', 'Dose menor', '2B', 'PharmGKB', 1),
('Furosemida', 'Diuréticos de Alça', 'GNB3', 'rs5443', 'target', 'GNB3 C825T modula resposta a diuréticos', 'Resposta padrão', 'Resposta variável', 'Melhor resposta', '3', 'PharmGKB', 1);

-- =============================================
-- PARTE B: Detalhes dos medicamentos
-- =============================================

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Hidrocodona', (SELECT id FROM pgx_drug_classes WHERE code='analgesico' LIMIT 1), 'Hysingla ER®, Zohydro ER®, Vicodin® (associada)', 'A hidrocodona é um opioide semi-sintético utilizado para dor moderada a intensa. É PARCIALMENTE convertida pelo CYP2D6 em hidromorfona (metabólito mais potente), mas o composto original também é ativo. Diferente do tramadol, a hidrocodona funciona mesmo sem CYP2D6, porém com eficácia parcialmente reduzida.', 'CYP2D6 (rs3892097) N/D. A hidrocodona funciona parcialmente sem CYP2D6 (diferente do tramadol que NÃO funciona). OPRM1 AA = receptor normal. COMT AG = resposta intermediária.', 'rs3892097', '22', 'CYP2D6', 'Europeia', 'CYP2D6 e Hidrocodona:\n- Composto original é parcialmente ativo (diferente do tramadol)\n- CYP2D6 converte em hidromorfona (mais potente)\n- Funciona mesmo em metabolizadores lentos, mas com menos potência', 'CYP2D6 indeterminado. Hidrocodona funciona parcialmente sem CYP2D6, mas para cirurgia maxilar, PREFERIR oxicodona ou morfina (que são completamente independentes do CYP2D6 para efeito analgésico).', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Hidroclorotiazida', (SELECT id FROM pgx_drug_classes WHERE code='cardio' LIMIT 1), 'Clorana®, Cloragio®, Diurix®, Hidromed®, Neo Hidroclor®', 'A hidroclorotiazida é um diurético tiazídico utilizado para hipertensão e edema. Genes NEDD4L e ADD1 modulam a resposta pressórica. A Genera identificou predisposição para MENOR taxa de resposta ao tratamento com hidroclorotiazida.', 'NEDD4L (rs4149601 GG) = NORMAL. ADD1 (rs4961 GG) = NORMAL (sem sensibilidade aumentada ao sódio). YEATS4 N/D. A Genera usou marcadores adicionais que identificaram menor resposta — possivelmente YEATS4 ou outro SNP não disponível em nosso painel.', 'rs4961', '4', 'ADD1', 'Europeia', 'ADD1 rs4961 (G460W):\n- GG = Normal (sensibilidade padrão ao sódio)\n- GT = Sensibilidade intermediária\n- TT = Alta sensibilidade ao sódio (melhor resposta a tiazídicos)\n\nNEDD4L rs4149601: GG = Normal\nYEATS4: N/D', 'ADD1 e NEDD4L normais (GG). A Genera identificou menor resposta à hidroclorotiazida — possivelmente por YEATS4 (não disponível). Se controle pressórico insuficiente com tiazídico, considerar associação ou alternativa. Monitorar eletrólitos (K, Na, Mg).', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Haloperidol', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Haldol®, Haloper®, Uni Haloper®', 'O haloperidol é um antipsicótico típico potente (butirofenona). Utilizado para psicoses, agitação aguda e Tourette. É metabolizado pelo CYP2D6. Em metabolizadores lentos, risco aumentado de EPS e discinesia. MC4R modula ganho de peso (menor que atípicos). Efeitos adversos incluem EPS, discinesia tardia, prolongamento QTc e síndrome neuroléptica maligna.', 'CYP2D6 N/D. MC4R (TT) = sem risco genético adicional de obesidade (haloperidol causa menos ganho de peso que atípicos).', 'rs3892097', '22', 'CYP2D6', 'Europeia', 'CYP2D6 rs3892097:\n- N/D\n\nMC4R rs17782313: TT = Normal', 'CYP2D6 indeterminado. Se haloperidol prescrito, iniciar dose baixa e monitorar EPS. MC4R normal. Haloperidol é eficaz mas com mais EPS que atípicos. Para autismo, preferir atípicos (risperidona/aripiprazol) como primeira linha.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Guanfacina', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Intuniv®, Tenex®', 'A guanfacina é um agonista alfa-2A adrenérgico NÃO-estimulante utilizado para TDAH. Melhora atenção e controle de impulsos sem risco de abuso. É metabolizada pelo CYP3A4. Efeitos adversos incluem sonolência, hipotensão, bradicardia e sedação.', 'CYP3A4 (rs35599367 GG) = metabolismo NORMAL. Guanfacina processada adequadamente.', 'rs35599367', '7', 'CYP3A4', 'Europeia', 'CYP3A4 rs35599367: GG = Normal', 'MUITO RELEVANTE PARA TDAH/AUTISMO: CYP3A4 normal. Guanfacina (Intuniv) é opção NÃO-estimulante para TDAH que NÃO depende do CYP2D6 (desconhecido). Pode ser usada como alternativa ou adjuvante ao metilfenidato. Boa para controle de impulsividade e regulação emocional em autistas. Titular lentamente.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Glimepirida', (SELECT id FROM pgx_drug_classes WHERE code='diabetes' LIMIT 1), 'Amaryl®, Amaglyn®, Azulix®, Betes®, Gliansor®', 'A glimepirida é uma sulfonilureia de segunda geração para diabetes tipo 2. Pode causar hemólise em deficientes de G6