-- =============================================
-- MEDIC - Seed de Detalhes de Medicamentos (Lote 20 de N)
-- 10 medicamentos: Celecoxibe → Bupropiona
-- Pode ser rodado múltiplas vezes com segurança
-- =============================================

SET NAMES utf8mb4;

-- =============================================
-- PARTE A: Inserir medicamentos na pgx_drug_genes
-- =============================================

INSERT IGNORE INTO `pgx_drug_genes` (`drug_name`, `drug_class`, `gene_symbol`, `rsid`, `interaction_type`, `effect_description`, `recommendation_normal`, `recommendation_het`, `recommendation_risk`, `evidence_level`, `source`, `is_active`) VALUES
('Celecoxibe', 'Anti-inflamatórios (AINEs/COX-2)', 'CYP2C9', 'rs1799853', 'substrate', 'CYP2C9 metaboliza celecoxibe', 'Dose padrão', 'Metabolismo reduzido', 'Risco de efeitos adversos', '2A', 'DPWG', 1),
('Ceftriaxona', 'Antibióticos (Cefalosporinas)', 'G6PD', 'rs1050829', 'risk', 'G6PD deficiente - risco teórico de hemólise', 'Sem risco', 'Cautela', 'Monitorar', '3', 'PharmGKB', 1),
('Carvedilol', 'Betabloqueadores', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza carvedilol', 'Dose padrão', 'Efeito beta-bloqueador aumentado', 'Hipotensão/bradicardia', '2A', 'PharmGKB', 1),
('Carisoprodol', 'Relaxantes Musculares', 'CYP2C19', 'rs12248560', 'substrate', 'CYP2C19 metaboliza carisoprodol em meprobamato', 'Dose padrão', 'Metabolismo aumentado - efeito menor', 'Efeito reduzido', '2B', 'PharmGKB', 1),
('Carbamazepina', 'Anticonvulsivantes/Estabilizadores', 'HLA-B', 'rs3909184', 'risk', 'HLA-B*15:02 - SJS/TEN em asiáticos', 'Sem risco (europeus)', 'Baixo risco', 'Tipagem HLA em asiáticos', '1A', 'CPIC', 1),
('Carbamazepina', 'Anticonvulsivantes/Estabilizadores', 'EPHX1', 'rs1051740', 'substrate', 'EPHX1 metaboliza epóxido da carbamazepina', 'Normal', 'Metabolismo reduzido do epóxido', 'Epóxido acumula - neurotoxicidade', '2B', 'PharmGKB', 1),
('Captopril', 'Inibidores da ECA', 'ACE', 'rs4343', 'target', 'ACE modula resposta a iECAs', 'Resposta padrão', 'Resposta intermediária', 'Níveis elevados - boa resposta', '2B', 'PharmGKB', 1),
('Capecitabina', 'Antineoplásicos (Fluoropirimidinas)', 'DPYD', 'rs3918290', 'substrate', 'DPD metaboliza capecitabina - deficiência FATAL', 'Dose padrão', 'Reduzir dose 25-50%', 'CONTRAINDICADO', '1A', 'CPIC', 1),
('Canabidiol', 'Canabinoides', 'CYP3A4', 'rs35599367', 'substrate', 'CYP3A4 metaboliza canabidiol', 'Dose padrão', 'Metabolismo reduzido', 'Monitorar', '2B', 'PharmGKB', 1),
('Canabidiol', 'Canabinoides', 'CYP2C19', 'rs12248560', 'substrate', 'CYP2C19 é via secundária do CBD', 'Normal', 'Metabolismo aumentado', 'Menos impacto', '3', 'PharmGKB', 1),
('Buspirona', 'Ansiolíticos', 'CYP3A4', 'rs35599367', 'substrate', 'CYP3A4 metaboliza buspirona', 'Dose padrão', 'Metabolismo reduzido', 'Níveis aumentados', '2A', 'PharmGKB', 1),
('Bupropiona', 'Antidepressivos', 'CYP2B6', 'rs3211371', 'substrate', 'CYP2B6 metaboliza bupropiona em hidroxibupropiona', 'Dose padrão', 'Metabolismo variável', 'Monitorar', '2A', 'PharmGKB', 1);

-- =============================================
-- PARTE B: Detalhes (principais)
-- =============================================

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Carbamazepina', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Tegretol®, Tegrex®, Teucarba®, Epizetol®', 'A carbamazepina é anticonvulsivante/estabilizador de humor para epilepsia, neuralgia do trigêmeo e bipolaridade. HLA-B*15:02 é risco de SJS (asiáticos). HLA-A*31:01 associado a hipersensibilidade em europeus (rash, febre, não SJS). EPHX1 metaboliza o epóxido ativo. Em europeus o risco de SJS é muito baixo.', 'HLA-B*15:02 proxy GG = provavelmente negativo. EPHX1 (rs1051740 TT) = metabolismo normal do epóxido de carbamazepina. Risco de neurotoxicidade por epóxido é padrão.', 'rs3909184', '6', 'HLA-B', 'Europeia', 'HLA-B*15:02: Risco SJS muito baixo em europeus\nEPHX1 rs1051740 (Y113H): TT = Normal (metabolismo adequado do epóxido)\n\nHLA-A*31:01: Não testado (associado a rash em europeus, não SJS)', 'Risco SJS muito baixo (europeu). EPHX1 normal (epóxido metabolizado adequadamente). Carbamazepina pode ser usada para epilepsia/neuralgia com monitoramento padrão. Para estabilização de humor em autistas, considerar também lamotrigina ou ácido valpróico. Titular lentamente e monitorar hemograma (raro: agranulocitose).', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Capecitabina', (SELECT id FROM pgx_drug_classes WHERE code='onco' LIMIT 1), 'Xeloda®, Capecare®, Capeliv®, Coama®, Colorretal®', 'A capecitabina é uma pró-droga oral do 5-FU utilizada para câncer colorretal e mama. Como o 5-FU, é inativada pela DPD. Deficiência de DPYD causa toxicidade FATAL. O CPIC EXIGE teste antes do uso.', 'DPYD rs3918290 (*2A) CC + rs67376798 (D949V) TT = DPYD NORMAL. Capecitabina segura do ponto de vista da DPD.', 'rs3918290', '1', 'DPYD', 'Europeia', 'DPYD Normal → Capecitabina/5-FU seguro\n\nNOTA: Confirmar interpretação de strand com laudo Genera (risco fatal).', 'DPYD normal. Capecitabina pode ser usada conforme protocolo oncológico. MESMA NOTA DE CAUTELA sobre interpretação de strand que para fluorouracila/tegafur.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Canabidiol', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Epidiolex®', 'O canabidiol (CBD) é utilizado para epilepsia refratária (Dravet, Lennox-Gastaut) e, off-label, para ansiedade, insônia e autismo. É metabolizado pelo CYP3A4 (principal) e CYP2C19 (secundário). NÃO é psicoativo (diferente do THC). Efeitos adversos incluem sonolência, diarreia, hepatotoxicidade e interações com anticonvulsivantes.', 'CYP3A4 (GG) = NORMAL. CYP2C19 *1/*17 = metabolismo levemente aumentado pela via secundária (impacto menor para CBD que para THC). COMT AG = intermediário (menos relevante para CBD que para THC pois CBD não é psicoativo).', 'rs35599367', '7', 'CYP3A4', 'Europeia', 'CYP3A4: GG = Normal (CBD metabolizado adequadamente)\nCYP2C19: CT (*17) = Via secundária levemente mais rápida\n\nNota: CBD NÃO é psicoativo (diferente do THC). COMT menos relevante.', 'RELEVANTE PARA AUTISMO/EPILEPSIA: CYP3A4 normal. CBD processado adequadamente. Para autismo, CBD é usado off-label para ansiedade, agressividade e insônia. Perfil farmacogenético favorável (não depende de CYP2D6, CYP3A4 normal). Interações com outros anticonvulsivantes (clobazam, valproato) devem ser monitoradas.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Bupropiona', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Wellbutrin®, Bup®, Zyban®', 'A bupropiona é um antidepressivo atípico (IRND - inibidor da recaptação de noradrenalina e dopamina) utilizado para depressão, cessação do tabagismo e TDAH (off-label). É metabolizada pelo CYP2B6 em hidroxibupropiona (metabólito ativo). NÃO depende do CYP2D6 nem CYP2C19 para efeito.', 'CYP2B6 (rs3211371) N/D. A bupropiona NÃO depende do CYP2D6 nem CYP2C19 — é metabolizada pelo CYP2B6. Tem mecanismo diferente dos ISRS/IRSN (atua em dopamina/noradrenalina). ANKK1 N/D.', 'rs3211371', '19', 'CYP2B6', 'Europeia', 'CYP2B6: N/D\n\nVantagens da bupropiona:\n- NÃO depende de CYP2D6 (desconhecido)\n- NÃO depende de CYP2C19 (rápido)\n- NÃO é ISRS (HTR1A CG não se aplica)\n- Não causa ganho de peso\n- Não causa disfunção sexual', 'MUITO RELEVANTE PARA AUTISMO/TDAH: A bupropiona é ALTERNATIVA com mecanismo diferente dos ISRS. NÃO é afetada por nenhum dos CYP problemáticos de Eric. Pode ser usada para: depressão (sem ganho peso, sem disfunção sexual), cessação tabagismo, e TDAH (off-label). CONTRAINDICADA em epilepsia (baixa limiar convulsivo).', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();