-- =============================================
-- MEDIC - Seed de Detalhes de Medicamentos (Lote 19 de N)
-- 10 medicamentos: Cloroquina → Cetamina
-- Pode ser rodado múltiplas vezes com segurança
-- =============================================

SET NAMES utf8mb4;

-- =============================================
-- PARTE A: Inserir medicamentos na pgx_drug_genes
-- =============================================

INSERT IGNORE INTO `pgx_drug_genes` (`drug_name`, `drug_class`, `gene_symbol`, `rsid`, `interaction_type`, `effect_description`, `recommendation_normal`, `recommendation_het`, `recommendation_risk`, `evidence_level`, `source`, `is_active`) VALUES
('Cloroquina', 'Antiparasitários (Antimaláricos)', 'G6PD', 'rs1050829', 'risk', 'G6PD deficiente - cloroquina pode causar hemólise', 'Sem risco', 'Cautela', 'Monitorar', '2A', 'CPIC', 1),
('Clopidogrel', 'Anticoagulantes (Antiplaquetários)', 'CYP2C19', 'rs12248560', 'substrate', 'CYP2C19 converte clopidogrel em metabólito ativo - *17 AUMENTA eficácia', 'Dose padrão', 'Eficácia AUMENTADA (boa notícia)', 'Eficácia muito aumentada', '1A', 'CPIC', 1),
('Clopidogrel', 'Anticoagulantes (Antiplaquetários)', 'CES1', 'rs2244613', 'substrate', 'CES1 modula ativação do clopidogrel', 'Normal', 'Ativação variável', 'Ativação reduzida', '3', 'PharmGKB', 1),
('Clonazepam', 'Ansiolíticos (Benzodiazepínicos)', 'CYP3A4', 'rs35599367', 'substrate', 'CYP3A4 metaboliza clonazepam', 'Dose padrão', 'Metabolismo reduzido', 'Acúmulo possível', '2B', 'PharmGKB', 1),
('Clomipramina', 'Antidepressivos (Tricíclicos)', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza clomipramina', 'Dose padrão', 'Monitorar', 'Reduzir dose', '1A', 'CPIC', 1),
('Clomipramina', 'Antidepressivos (Tricíclicos)', 'CYP2C19', 'rs12248560', 'substrate', 'CYP2C19 é via secundária - *17 aumenta metabolismo', 'Dose padrão', 'Metabolismo aumentado', 'Pode necessitar dose maior', '2A', 'CPIC', 1),
('Clobazam', 'Ansiolíticos/Anticonvulsivantes', 'CYP2C19', 'rs12248560', 'substrate', 'CYP2C19 metaboliza clobazam em N-desmetilclobazam - *17 elimina mais rápido', 'Dose padrão', 'Duração pode ser menor', 'Duração reduzida', '1A', 'CPIC', 1),
('Citalopram', 'Antidepressivos (ISRS)', 'CYP2C19', 'rs12248560', 'substrate', 'CYP2C19*17 aumenta metabolismo do citalopram', 'Dose padrão', 'Níveis 30-40% menores', 'Considerar alternativa', '1A', 'CPIC', 1),
('Citalopram', 'Antidepressivos (ISRS)', 'HTR2A', 'rs6311', 'target', 'HTR2A modula resposta', 'Normal', 'Variável', 'Variável', '2B', 'PharmGKB', 1),
('Cisplatina', 'Antineoplásicos', 'TPMT', 'rs1800460', 'risk', 'TPMT modula risco de ototoxicidade com cisplatina', 'Risco padrão', 'Risco aumentado de ototoxicidade', 'Risco alto', '2A', 'CPIC', 1),
('Ciprofloxacina', 'Antibióticos (Fluoroquinolonas)', 'G6PD', 'rs1050829', 'risk', 'G6PD deficiente - risco de hemólise', 'Sem risco', 'Cautela', 'Monitorar', '3', 'PharmGKB', 1),
('Ciclosporina', 'Imunossupressores', 'CYP3A5', 'rs776746', 'substrate', 'CYP3A5 metaboliza ciclosporina - expressores necessitam dose maior', 'Dose padrão (não-expressor)', 'Dose maior necessária (expressor parcial)', 'Dose significativamente maior', '2A', 'PharmGKB', 1),
('Cetamina', 'Anestésicos/Antidepressivos', 'CYP2B6', 'rs3211371', 'substrate', 'CYP2B6 metaboliza cetamina em norketamina', 'Dose padrão', 'Metabolismo variável', 'Monitorar', '3', 'PharmGKB', 1);

-- =============================================
-- PARTE B: Detalhes (principais)
-- =============================================

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Clopidogrel', (SELECT id FROM pgx_drug_classes WHERE code='cardio' LIMIT 1), 'Plavix®, Clopiplax®, Cuore®, Dogrelix®, Plaq®, Plaquevix®', 'O clopidogrel é um antiplaquetário PRÓ-DROGA que PRECISA ser ativado pelo CYP2C19. Em metabolizadores lentos (*2/*2), é INEFICAZ. Em metabolizadores RÁPIDOS (*17), a eficácia é AUMENTADA (mais metabólito ativo). O CPIC recomenda ticagrelor/prasugrel para metabolizadores lentos.', 'CYP2C19 *1/*17 (CT) = METABOLIZADOR RÁPIDO. Para clopidogrel, isso é FAVORÁVEL — mais metabólito ativo é produzido, com eficácia antiplaquetária AUMENTADA. CES1 (TT) = normal.', 'rs12248560', '10', 'CYP2C19', 'Europeia', 'CYP2C19 e Clopidogrel (CPIC):\n- *1/*1 = Normal (eficácia adequada)\n- *1/*17 = Metabolizador rápido → EFICÁCIA AUMENTADA (boa notícia!)\n- *17/*17 = Ultra-rápido → Eficácia ainda maior\n- *1/*2 = Intermediário → Eficácia reduzida (considerar alternativa)\n- *2/*2 = Lento → INEFICAZ (usar ticagrelor)', 'CYP2C19 *1/*17 é FAVORÁVEL para clopidogrel (diferente dos IBPs!). O clopidogrel funciona BEM neste paciente — a ativação é AUMENTADA. Se antiplaquetário for necessário, clopidogrel é opção adequada (não precisa de ticagrelor por motivo genético, embora ticagrelor funcione independente do CYP2C19).', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Clobazam', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Frisium®, Onfi®, Sympazan®', 'O clobazam é um benzodiazepínico 1,5- utilizado como anticonvulsivante adjuvante (epilepsia) e ansiolítico. É metabolizado pelo CYP2C19 em N-desmetilclobazam (metabólito ativo). O CPIC tem guideline: em metabolizadores lentos, o metabólito ACUMULA com mais sedação.', 'CYP2C19 *1/*17 (CT) = METABOLIZADOR RÁPIDO. O clobazam e seu metabólito ativo podem ser eliminados mais rapidamente, com duração potencialmente MENOR do efeito anticonvulsivante.', 'rs12248560', '10', 'CYP2C19', 'Europeia', 'CYP2C19 e Clobazam (CPIC):\n- *1/*1 = Normal\n- *1/*17 = Rápido (duração pode ser menor)\n- *2/*2 = Lento (metabólito ACUMULA - sedação excessiva)', 'CYP2C19 *1/*17. Clobazam pode ter duração MENOR. Se usado como anticonvulsivante, monitorar controle de crises. Pode necessitar ajuste de dose ou frequência. Para ansiedade, considerar lorazepam (não depende CYP) como alternativa.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Ciclosporina', (SELECT id FROM pgx_drug_classes WHERE code='imuno_transplante' LIMIT 1), 'Sandimmun®, Restasis®', 'A ciclosporina é um imunossupressor inibidor da calcineurina utilizado para transplantes e doenças autoimunes. É metabolizada pelo CYP3A4/CYP3A5. Em expressores do CYP3A5, metabolismo aumentado com necessidade de dose maior (similar ao tacrolimo).', 'CYP3A5 (rs776746 CT) = EXPRESSOR PARCIAL. A ciclosporina pode ser eliminada mais rapidamente, necessitando dose potencialmente MAIOR (similar ao tacrolimo). TDM obrigatório.', 'rs776746', '7', 'CYP3A5', 'Europeia', 'CYP3A5 rs776746 e Ciclosporina:\n- GG/AA (não-expressor) = Dose padrão\n- CT/AG (expressor parcial) = Pode necessitar dose maior\n- CC/TT (expressor) = Dose significativamente maior\n\nTDM obrigatório.', 'CYP3A5 expressor parcial (CT). Ciclosporina pode necessitar dose MAIOR (similar ao tacrolimo). Monitoramento de níveis séricos (TDM) é OBRIGATÓRIO. Achado consistente com o do tacrolimo.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Cetamina', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Ketalar®, Cetamin®, Ketamin-S®', 'A cetamina é um anestésico dissociativo utilizado para anestesia, dor crônica e depressão resistente (infusão IV/intranasal Spravato). É metabolizada pelo CYP2B6 em norketamina. NÃO depende do CYP2D6. Efeitos adversos incluem dissociação, alucinações, náuseas, hipertensão e potencial de abuso.', 'CYP2B6 (rs3211371) N/D. A cetamina NÃO depende do CYP2D6 nem CYP2C19 — é uma opção com MENOS incerteza farmacogenética para este paciente.', 'rs3211371', '19', 'CYP2B6', 'Europeia', 'CYP2B6: N/D\n\nNota: Cetamina NÃO depende de CYP2D6, CYP2C19 nem CYP3A4.', 'RELEVANTE PARA CIRURGIA + DEPRESSÃO RESISTENTE: CYP2B6 indeterminado mas cetamina tem MENOS dependência dos CYP450 conhecidos. Para anestesia na cirurgia maxilar, pode ser usada como adjuvante (efeito analgésico + dissociativo). Para depressão resistente (off