-- =============================================
-- MEDIC - Seed de Detalhes de Medicamentos (Lote 12 de N)
-- 10 medicamentos: Levodopa → Hidroxicloroquina
-- Pode ser rodado múltiplas vezes com segurança
-- =============================================

SET NAMES utf8mb4;

-- =============================================
-- PARTE A: Inserir medicamentos na pgx_drug_genes
-- =============================================

INSERT IGNORE INTO `pgx_drug_genes` (`drug_name`, `drug_class`, `gene_symbol`, `rsid`, `interaction_type`, `effect_description`, `recommendation_normal`, `recommendation_het`, `recommendation_risk`, `evidence_level`, `source`, `is_active`) VALUES
('Levodopa', 'Antiparkinsonianos', 'COMT', 'rs4680', 'target', 'COMT degrada dopamina - afeta duração da levodopa', 'Duração padrão', 'Duração intermediária da levodopa', 'Duração maior (COMT baixa = mais dopamina)', '2A', 'PharmGKB', 1),
('Levodopa-Carbidopa-Entacapona', 'Antiparkinsonianos', 'COMT', 'rs4680', 'target', 'COMT é inibida pela entacapona - genótipo modula resposta', 'Resposta padrão', 'Resposta intermediária', 'Melhor resposta à entacapona', '2B', 'PharmGKB', 1),
('Lansoprazol', 'IBPs (Inibidores de Bomba de Prótons)', 'CYP2C19', 'rs12248560', 'substrate', 'CYP2C19 metaboliza lansoprazol - *17 reduz eficácia', 'Dose padrão', 'Eficácia reduzida', 'Eficácia muito reduzida', '1A', 'CPIC', 1),
('Lamotrigina', 'Anticonvulsivantes/Estabilizadores', 'HLA-B', 'rs3909184', 'risk', 'HLA-B*15:02 associado a SJS - risco em asiáticos', 'Sem risco (europeus)', 'Baixo risco', 'Tipagem HLA em asiáticos', '1A', 'CPIC', 1),
('Irbesartana', 'Antagonistas de Angiotensina II (BRAs)', 'CYP2C9', 'rs1799853', 'substrate', 'CYP2C9 metaboliza irbesartana', 'Dose padrão', 'Metabolismo reduzido - níveis maiores', 'Níveis aumentados', '2A', 'PharmGKB', 1),
('Imipramina', 'Antidepressivos (Tricíclicos)', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza imipramina em desipramina', 'Dose padrão', 'Monitorar níveis', 'Reduzir dose 50%', '1A', 'CPIC', 1),
('Imipramina', 'Antidepressivos (Tricíclicos)', 'CYP2C19', 'rs12248560', 'substrate', 'CYP2C19 é via secundária - *17 aumenta metabolismo', 'Dose padrão', 'Metabolismo aumentado', 'Pode necessitar dose maior', '1A', 'CPIC', 1),
('Imatinibe', 'Antineoplásicos (Inibidores de Tirosina Quinase)', 'CYP1A2', 'rs762551', 'substrate', 'CYP1A2 metaboliza parcialmente imatinibe', 'Dose padrão', 'Metabolismo aumentado', 'Monitorar resposta', '2B', 'PharmGKB', 1),
('Iloperidona', 'Antipsicóticos', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza iloperidona', 'Dose padrão', 'Monitorar', 'Reduzir dose 50%', '1A', 'FDA', 1),
('Ibuprofeno', 'Anti-inflamatórios (AINEs)', 'CYP2C9', 'rs1799853', 'substrate', 'CYP2C9 metaboliza ibuprofeno', 'Dose padrão', 'Meia-vida prolongada', 'Risco de sangramento GI', '2A', 'DPWG', 1),
('Hidroxicloroquina', 'Antiparasitários/Imunossupressores', 'G6PD', 'rs1050829', 'risk', 'G6PD deficiente - risco de hemólise', 'Sem risco', 'Cautela', 'Monitorar hemograma', '2A', 'CPIC', 1);

-- =============================================
-- PARTE B: Detalhes dos medicamentos (resumidos)
-- =============================================

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Levodopa', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Sinemet®', 'A levodopa é o tratamento padrão-ouro para Parkinson. É convertida em dopamina no cérebro. A COMT degrada a dopamina perifericamente, reduzindo a disponibilidade. O genótipo COMT modula a duração do efeito.', 'COMT (rs4680 AG = Val/Met) = atividade INTERMEDIÁRIA. A duração da levodopa é intermediária — pode necessitar de doses mais frequentes ou adição de entacapona (inibidor da COMT).', 'rs4680', '22', 'COMT', 'Europeia', 'COMT rs4680 e Levodopa:\n- AA (Met/Met) = COMT baixa → Dopamina dura mais\n- AG (Val/Met) = Intermediário\n- GG (Val/Val) = COMT alta → Dopamina degradada rápido', 'COMT AG = intermediário. Se levodopa for necessária, monitorar wearing-off. Pode se beneficiar de entacapona (Stalevo) para prolongar efeito.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Levodopa-Carbidopa-Entacapona', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Stalevo®, Carbidol® (L+C), Parkidopa® (L+C)', 'Combinação de levodopa + inibidor de DOPA descarboxilase (carbidopa) + inibidor da COMT (entacapona). A entacapona INIBE a COMT, prolongando o efeito da levodopa. O genótipo COMT pode modular quão benéfica é a entacapona.', 'COMT AG = atividade intermediária. A entacapona bloqueia a COMT residual, podendo beneficiar pacientes com atividade intermediária/alta.', 'rs4680', '22', 'COMT', 'Europeia', 'COMT e Entacapona:\n- AA (COMT baixa) = Pode ter menos benefício adicional da entacapona\n- AG = Benefício intermediário\n- GG (COMT alta) = Maior benefício da entacapona', 'COMT AG = benefício intermediário da entacapona. Se wearing-off for problema, Stalevo é opção racional.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Lansoprazol', (SELECT id FROM pgx_drug_classes WHERE code='gastro' LIMIT 1), 'Ogastro®, Lanz®, Prazol®, Laflugi®', 'O lansoprazol é um IBP MUITO dependente do CYP2C19. Em metabolizadores rápidos (*1/*17), a eficácia é significativamente reduzida (similar ao omeprazol). O CPIC recomenda dose maior ou alternativa.', 'CYP2C19 *1/*17 (CT) = METABOLIZADOR RÁPIDO. Lansoprazol tem eficácia REDUZIDA (similar ao omeprazol). Preferir rabeprazol.', 'rs12248560', '10', 'CYP2C19', 'Europeia', 'CYP2C19 e Lansoprazol:\n- *1/*1 = Normal\n- *1/*17 = Eficácia reduzida (como omeprazol)\n- Preferir RABEPRAZOL', 'CYP2C19 rápido. Lansoprazol = omeprazol em termos de impacto do CYP2C19. PREFERIR RABEPRAZOL. Se usar lansoprazol, dose maior (30mg 2x/dia).', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Lamotrigina', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Lamictal®, Exafob®, Lamorgin®, Lamitor®, Léptico®', 'A lamotrigina é anticonvulsivante/estabilizador de humor para epilepsia e bipolaridade. O HLA-B*15:02 é fator de risco para SJS/TEN (principalmente em asiáticos). Em europeus o risco é muito baixo. Metabolizada por UGT1A4. Efeitos adversos incluem rash (titular lentamente!), tontura, diplopia e cefaleia.', 'HLA-B*15:02 proxy GG = provavelmente NEGATIVO. Ancestralidade 92% europeia = risco SJS muito baixo. NÃO se aplica a indicação de tipagem HLA obrigatória (que é para asiáticos).', 'rs3909184', '6', 'HLA-B', 'Europeia (risco SJS muito baixo)', 'HLA-B*15:02:\n- Europeus: Risco muito baixo independente do HLA\n- Asiáticos: Tipagem obrigatória\n\nNota: Titular LENTAMENTE sempre (25mg por 2 semanas → aumentar)', 'Risco de SJS muito baixo (europeu). Lamotrigina pode ser usada com titulação lenta obrigatória. Boa opção como estabilizador de humor em autistas/bipolaridade (não causa ganho de peso).', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Irbesartana', (SELECT id FROM pgx_drug_classes WHERE code='cardio' LIMIT 1), 'Aprovel®, Bart®, Irbe®, Irbeless®, Lestric®, Irtana®', 'A irbesartana é um BRA. Diferente da losartana, NÃO é pró-droga — já é ativa. O CYP2C9 metaboliza irbesartana para eliminação. Em metabolizadores lentos, níveis maiores (mas medicamento já ativo).', 'CYP2C9 CC = normal. Irbesartana metabolizada adequadamente.', 'rs1799853', '10', 'CYP2C9', 'Europeia', 'CYP2C9 e Irbesartana:\n- CC = Normal\n-