-- =============================================
-- MEDIC - Seed de Detalhes de Medicamentos (Lote 18 de N)
-- 10 medicamentos: Desvenlafaxina → Clorpromazina
-- Pode ser rodado múltiplas vezes com segurança
-- =============================================

SET NAMES utf8mb4;

-- =============================================
-- PARTE A: Inserir medicamentos na pgx_drug_genes
-- =============================================

INSERT IGNORE INTO `pgx_drug_genes` (`drug_name`, `drug_class`, `gene_symbol`, `rsid`, `interaction_type`, `effect_description`, `recommendation_normal`, `recommendation_het`, `recommendation_risk`, `evidence_level`, `source`, `is_active`) VALUES
('Desvenlafaxina', 'Antidepressivos (IRSN)', 'FKBP5', 'rs1360780', 'target', 'FKBP5 modula resposta a antidepressivos', 'Resposta favorável', 'Eixo HPA desregulado', 'Resposta reduzida', '2B', 'PharmGKB', 1),
('Desipramina', 'Antidepressivos (Tricíclicos)', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza desipramina - CPIC guideline', 'Dose padrão', 'Monitorar níveis', 'Reduzir dose 50%', '1A', 'CPIC', 1),
('Desipramina', 'Antidepressivos (Tricíclicos)', 'BDNF', 'rs6265', 'target', 'BDNF modula resposta', 'Normal', 'Secreção reduzida', 'Resposta reduzida', '2B', 'PharmGKB', 1),
('Daunorrubicina', 'Antineoplásicos (Antraciclinas)', 'RARG', 'rs2229774', 'risk', 'RARG S427L - cardiotoxicidade com antraciclinas', 'Risco padrão', 'RISCO AUMENTADO', 'Risco muito aumentado', '2A', 'CPGG', 1),
('Daunorrubicina', 'Antineoplásicos (Antraciclinas)', 'SLC28A3', 'rs7853758', 'risk', 'SLC28A3 efeito protetor', 'Sem proteção', 'Proteção parcial', 'Proteção', '2B', 'PharmGKB', 1),
('Darifenacina', 'Antimuscarínicos', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 metaboliza darifenacina', 'Dose padrão', 'Monitorar anticolinérgicos', 'Dose menor', '2A', 'PharmGKB', 1),
('Dapsona', 'Antibióticos (Sulfonas)', 'G6PD', 'rs1050829', 'risk', 'G6PD deficiente - dapsona causa hemólise', 'Sem risco', 'Cautela', 'CONTRAINDICADO se deficiente grave', '1A', 'CPIC', 1),
('Dabrafenibe', 'Antineoplásicos', 'G6PD', 'rs1050829', 'risk', 'G6PD deficiente - dabrafenibe pode causar hemólise', 'Sem risco', 'Teste G6PD', 'Monitorar', '2A', 'FDA', 1),
('Dabigatrana', 'Anticoagulantes (DOACs)', 'CES1', 'rs2244613', 'substrate', 'CES1 ativa dabigatrana (pró-droga)', 'Ativação normal', 'Ativação variável', 'Ativação reduzida', '3', 'PharmGKB', 1),
('Codeína', 'Analgésicos Opioides', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 converte codeína em morfina - ESSENCIAL. Sem CYP2D6 = INEFICAZ', 'Dose padrão (morfina produzida)', 'Analgesia reduzida', 'Codeína INEFICAZ - usar alternativa', '1A', 'CPIC', 1),
('Clozapina', 'Antipsicóticos', 'CYP2D6', 'rs3892097', 'substrate', 'CYP2D6 é via secundária da clozapina', 'Dose padrão', 'Monitorar', 'Monitorar', '2B', 'PharmGKB', 1),
('Clozapina', 'Antipsicóticos', 'MC4R', 'rs17782313', 'risk', 'MC4R modula ganho de peso', 'Sem risco aumentado', 'Risco moderado', 'Risco alto', '2B', 'PharmGKB', 1),
('Clozapina', 'Antipsicóticos', 'HTR2C', 'rs3813929', 'risk', 'HTR2C modula ganho de peso', 'Risco padrão', 'Proteção parcial', 'Proteção', '2B', 'PharmGKB', 1),
('Clorpromazina', 'Antipsicóticos', 'CYP1A2', 'rs762551', 'substrate', 'CYP1A2 metaboliza clorpromazina - ultra-rápidos eliminam mais rápido', 'Dose padrão', 'Metabolismo aumentado', 'Pode necessitar dose maior', '2B', 'PharmGKB', 1);

-- =============================================
-- PARTE B: Detalhes (principais)
-- =============================================

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Desvenlafaxina', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Pristiq®, Khedezla®, Desve®', 'A desvenlafaxina é o metabólito ativo da venlafaxina (O-desmetilvenlafaxina). Vantagem: NÃO precisa ser ativada pelo CYP2D6 (já é o metabólito final). É um IRSN direto. FKBP5 modula resposta.', 'FKBP5 (rs1360780 CC) = eixo HPA NORMAL — favorável para resposta. A desvenlafaxina NÃO depende do CYP2D6 (diferente da venlafaxina). É alternativa quando CYP2D6 é desconhecido.', 'rs1360780', '6', 'FKBP5', 'Europeia', 'FKBP5 rs1360780: CC = Normal (favorável)\n\nVantagem: NÃO depende de CYP2D6 (diferente da venlafaxina que depende).', 'RELEVANTE PARA AUTISMO: FKBP5 favorável. A desvenlafaxina é ALTERNATIVA PREFERENCIAL à venlafaxina quando CYP2D6 é desconhecido, pois já é o metabólito ativo. É IRSN (como duloxetina) — melhor que ISRS dado HTR1A CG (-30%). Opção para depressão + ansiedade sem incerteza do CYP2D6.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Codeína', (SELECT id FROM pgx_drug_classes WHERE code='analgesico' LIMIT 1), 'Codein®, Cod®, Tylex® (associada)', 'A codeína é uma PRÓ-DROGA que PRECISA ser convertida pelo CYP2D6 em morfina para ter efeito analgésico. SEM CYP2D6 funcional, a codeína NÃO funciona como analgésico. Em metabolizadores ultra-rápidos, risco de toxicidade (excesso de morfina). O CPIC RECOMENDA alternativa em metabolizadores lentos.', 'CYP2D6 (rs3892097) N/D. A codeína depende CRITICAMENTE do CYP2D6 (como tramadol). Sem saber o CYP2D6, NÃO é possível garantir que codeína será eficaz.', 'rs3892097', '22', 'CYP2D6', 'Europeia', 'CYP2D6 e Codeína (CPIC):\n- Normal = Dose padrão (morfina produzida)\n- Intermediário = Analgesia parcial\n- Metabolizador lento → Codeína INEFICAZ (não produz morfina)\n- Ultra-rápido → PERIGO: excesso de morfina (toxicidade/morte)\n\nNota: Codeína = Tramadol em termos de dependência do CYP2D6', 'ALERTA PARA CIRURGIA: CYP2D6 desconhecido = codeína NÃO deve ser usada. Se for metabolizador lento → não funciona. Se for ultra-rápido → risco de toxicidade grave. USAR ALTERNATIVAS: paracetamol + oxicodona, morfina, ou AINEs (CYP2C9 normal).', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Daunorrubicina', (SELECT id FROM pgx_drug_classes WHERE code='onco' LIMIT 1), 'Daunoblastina®, Evoclass®', 'A daunorrubicina é uma antraciclina utilizada para leucemias agudas. Mesmo perfil de cardiotoxicidade que doxorrubicina — RARG modula risco.', 'RARG (rs2229774 GA) = RISCO AUMENTADO de cardiotoxicidade (mesmo que doxorrubicina). SLC28A3 (GA) = proteção parcial.', 'rs2229774', '12', 'RARG', 'Europeia', 'RARG rs2229774: GA = Risco aumentado de cardiotoxicidade\nSLC28A3 rs7853758: GA = Proteção parcial', 'Mesmo achado da doxorrubicina: RARG GA = risco cardiotóxico aumentado. Monitoramento cardíaco obrigatório. Considerar dexrazoxano protetor.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid), chromosome=VALUES(chromosome), gene_symbol=VALUES(gene_symbol), study_population=VALUES(study_population), genotype_results=VALUES(genotype_results), suggestions=VALUES(suggestions), disclaimer=VALUES(disclaimer), updated_at=NOW();

INSERT INTO `pgx_drug_details` (`drug_name`, `class_id`, `commercial_names`, `description`, `understanding_result`, `snp_rsid`, `chromosome`, `gene_symbol`, `study_population`, `genotype_results`, `suggestions`, `disclaimer`, `is_active`)
VALUES ('Clozapina', (SELECT id FROM pgx_drug_classes WHERE code='psiq_neuro' LIMIT 1), 'Leponex®, Pinazan®, Xynaz®', 'A clozapina é o antipsicótico mais eficaz (reservado para esquizofrenia refratária). Metabolizada pelo CYP1A2 (principal), CYP2D6 (secundário). Risco de agranulocitose (hemograma obrigatório). MC4R e HTR2C modulam ganho de peso (significativo).', 'CYP1A2 (CA = ultra-rápido) pode reduzir níveis. CYP2D6 N/D (via secundária). MC4R TT + HTR2C CC = sem risco GENÉTICO adicional de obesidade (mas clozapina causa ganho significativo independente).', 'rs762551', '15', 'CYP1A2', 'Europeia', 'CYP1A2: CA = Ultra-rápido (níveis podem ser menores)\nCYP2D6: N/D (via secundária)\nMC4R: TT = Normal\nHTR2C: CC = Risco padrão\n\nNota: Clozapina causa ganho de peso INDEPENDENTE da genética.', 'CYP1A2 ultra-rápido — clozapina pode ter níveis MENORES. Dose pode precisar ser maior. MC4R/HTR2C normais mas clozapina causa ganho significativo em todos. Hemograma OBRIGATÓRIO (agranulocitose). Reservada para refratariedade.', 'Nunca inicie, interrompa ou altere tratamentos sem orientação médica.', 1) ON DUPLICATE KEY UPDATE class_id=VALUES(class_id), commercial_names=VALUES(commercial_names), description=VALUES(description), understanding_result=VALUES(understanding_result), snp_rsid=VALUES(snp_rsid